// Consumer-facing copy shared by the homepage and the two filtering explainers.
// Product availability is intentionally not asserted here.
export const consumer = {
  en: {
    metaTitle: 'Filter images and video with a policy that fits you | Browslium',
    metaDescription: 'See how Browslium filters images and video with seven image levels and six video levels. Explore examples, Android app filtering, and plans for audio and text.',
    hero: ['Choose what you see online.', 'Browslium helps you filter images and video according to the level you choose. See the difference for yourself, one step at a time.', 'Explore image levels', 'See video levels'],
    heroVisual: ['The original image', 'With a filter', 'Your choice, a clearer view'],
    imageEyebrow: 'Image filtering', videoEyebrow: 'Video filtering',
    imageLevels: ['Show the original', 'Visible features', 'Women', 'Women and clothing', 'Women and shape', 'Clothing and shape', 'Block image: women', 'Block image: clothing'],
    videoLevels: ['Show the original', 'Women', 'Women and clothing', 'Women and shape', 'Clothing and shape', 'Block video: women', 'Block video: clothing'],
    levelGuide: 'Choose a level to see what it changes.', sceneGuide: 'Choose an example',
    compareHint: 'Drag the line to compare the original with the filtered image.',
    afterImages: 'Continue to video filtering', afterVideos: 'See audio and text',
    audio: ['Filtering can go beyond pictures', 'Audio and text call for their own analysis. Browslium is developing ways to apply selected policies to supported spoken and written content.', 'Audio', 'Analysis for supported audio, with rules suited to sound.', 'Text', 'Analysis for supported written content, with rules suited to words.', 'See filtering on Android'],
    android: ['Images inside Android apps matter too', 'People see content in apps as well as in browsers. Browslium is being developed to evaluate supported images inside Android apps and apply the selected image policy.', 'Content within apps', 'A choice of seven image levels', 'Focus on the item you see', 'Explore supported devices'],
    platforms: ['For the devices in your day', 'Browslium is being built across major platforms. The experience and supported features depend on the device.', [['Android', 'Filtering designed for supported content inside apps.'], ['iOS', 'A considered experience for iPhone and iPad.'], ['macOS', 'Filtering designed for the Mac.'], ['Windows', 'Filtering designed for Windows devices.']], 'See who it is for'],
    audiences: ['A filter for your own standards', 'Whether you use a device alone or share it with others, choose the level that matches what you want to see.', ['For yourself', 'For your family', 'For learning spaces', 'For your community'], 'Read common questions'],
    faqIntro: 'Answers about what Browslium filters, how levels work, and where it is being developed.',
    donate: ['Help Maintain Browslium', 'Contributions help keep the people and infrastructure behind the filter running.', 'Support Browslium'],
    slogan: 'Intelligent Protection for Safer Browsing',
  },
  es: {
    metaTitle: 'Filtra imágenes y videos a tu manera | Browslium',
    metaDescription: 'Mira cómo Browslium filtra imágenes y videos con siete niveles para fotos y seis para video. Explora ejemplos, el filtrado en apps de Android y los planes para audio y texto.',
    hero: ['Elige lo que quieres ver en internet.', 'Browslium te ayuda a filtrar imágenes y videos según el nivel que elijas. Mira la diferencia con ejemplos claros.', 'Explorar niveles de imagen', 'Ver niveles de video'],
    heroVisual: ['Imagen original', 'Con el filtro', 'Tu elección, una vista más clara'],
    imageEyebrow: 'Filtrado de imágenes', videoEyebrow: 'Filtrado de video',
    imageLevels: ['Ver original', 'Rasgos visibles', 'Mujeres', 'Mujeres y ropa', 'Mujeres y forma', 'Ropa y forma', 'Bloquear: mujeres', 'Bloquear: ropa'],
    videoLevels: ['Ver original', 'Mujeres', 'Mujeres y ropa', 'Mujeres y forma', 'Ropa y forma', 'Bloquear: mujeres', 'Bloquear: ropa'],
    levelGuide: 'Elige un nivel para ver qué cambia.', sceneGuide: 'Elige un ejemplo',
    compareHint: 'Desliza la línea para comparar la imagen original con la filtrada.',
    afterImages: 'Continuar al video', afterVideos: 'Conocer audio y texto',
    audio: ['El filtrado va más allá de las imágenes', 'El audio y el texto necesitan un análisis propio. Browslium desarrolla formas de aplicar las políticas elegidas al contenido hablado y escrito compatible.', 'Audio', 'Análisis del audio compatible con reglas pensadas para el sonido.', 'Texto', 'Análisis del texto compatible con reglas pensadas para las palabras.', 'Ver el filtrado en Android'],
    android: ['También importan las imágenes dentro de las apps de Android', 'Vemos contenido tanto en aplicaciones como en navegadores. Browslium se desarrolla para evaluar imágenes compatibles dentro de apps de Android y aplicar el nivel elegido.', 'Contenido dentro de las apps', 'Siete niveles de imagen para elegir', 'Atención al elemento que ves', 'Explorar dispositivos'],
    platforms: ['Para los dispositivos que usas', 'Browslium se desarrolla para las principales plataformas. La experiencia y las funciones compatibles dependen del dispositivo.', [['Android', 'Filtrado pensado para contenido compatible dentro de apps.'], ['iOS', 'Una experiencia pensada para iPhone y iPad.'], ['macOS', 'Filtrado diseñado para Mac.'], ['Windows', 'Filtrado diseñado para equipos Windows.']], 'Ver para quién es'],
    audiences: ['Un filtro según tus propias preferencias', 'Ya sea un dispositivo personal o compartido, elige el nivel que se ajuste a lo que quieres ver.', ['Para ti', 'Para tu familia', 'Para espacios educativos', 'Para tu comunidad'], 'Leer preguntas frecuentes'],
    faqIntro: 'Respuestas sobre qué filtra Browslium, cómo funcionan los niveles y para qué plataformas se desarrolla.',
    donate: ['Ayuda a mantener Browslium', 'Tu aportación ayuda a sostener al equipo y la infraestructura que mantienen el filtro.', 'Apoyar Browslium'],
    slogan: 'Intelligent Protection for Safer Browsing',
  },
  ru: {
    metaTitle: 'Фильтрация изображений и видео по вашим правилам | Browslium',
    metaDescription: 'Посмотрите, как Browslium фильтрует изображения и видео: семь уровней для изображений и шесть для видео. Примеры, Android-приложения, аудио и текст.',
    hero: ['Выбирайте, что видеть в интернете.', 'Browslium помогает фильтровать изображения и видео по выбранному вами уровню. Посмотрите на наглядные примеры.', 'Уровни для изображений', 'Уровни для видео'],
    heroVisual: ['Исходное изображение', 'С фильтром', 'Ваш выбор — яснее экран'],
    imageEyebrow: 'Фильтрация изображений', videoEyebrow: 'Фильтрация видео',
    imageLevels: ['Оригинал', 'Видимые черты', 'Женщины', 'Женщины и одежда', 'Женщины и форма', 'Одежда и форма', 'Блокировка: женщины', 'Блокировка: одежда'],
    videoLevels: ['Оригинал', 'Женщины', 'Женщины и одежда', 'Женщины и форма', 'Одежда и форма', 'Блокировка: женщины', 'Блокировка: одежда'],
    levelGuide: 'Выберите уровень и посмотрите, что изменится.', sceneGuide: 'Выберите пример',
    compareHint: 'Передвигайте линию, чтобы сравнить исходное и отфильтрованное изображение.',
    afterImages: 'Перейти к видео', afterVideos: 'Узнать про аудио и текст',
    audio: ['Не только изображения', 'Для аудио и текста нужны собственные методы анализа. Browslium разрабатывает правила для поддерживаемой речи и письменного контента.', 'Аудио', 'Анализ поддерживаемого звука по соответствующим правилам.', 'Текст', 'Анализ поддерживаемого текста по соответствующим правилам.', 'Фильтрация на Android'],
    android: ['Изображения в Android-приложениях тоже важны', 'Контент встречается не только в браузере. Browslium разрабатывается для оценки поддерживаемых изображений внутри Android-приложений по выбранным правилам.', 'Контент в приложениях', 'Семь уровней для изображений', 'Внимание к отдельному элементу', 'Устройства'],
    platforms: ['Для привычных устройств', 'Browslium разрабатывается для основных платформ. Возможности зависят от устройства.', [['Android', 'Фильтрация поддерживаемого контента в приложениях.'], ['iOS', 'Продуманный подход для iPhone и iPad.'], ['macOS', 'Фильтрация для Mac.'], ['Windows', 'Фильтрация для устройств Windows.']], 'Для кого это'],
    audiences: ['Фильтр по вашим правилам', 'Для личного или общего устройства можно выбрать уровень, который отвечает вашим предпочтениям.', ['Для себя', 'Для семьи', 'Для учёбы', 'Для сообщества'], 'Частые вопросы'],
    faqIntro: 'О том, что фильтрует Browslium, как работают уровни и для каких платформ он разрабатывается.',
    donate: ['Помогите поддерживать Browslium', 'Ваш вклад помогает содержать команду и инфраструктуру, от которых зависит работа фильтра.', 'Поддержать Browslium'],
    slogan: 'Intelligent Protection for Safer Browsing',
  },
  yi: {
    metaTitle: 'פֿילטערן בילדער און ווידעאָס לויט אײַער אויסוואַל | Browslium',
    metaDescription: 'זעט ווי Browslium פֿילטערט בילדער און ווידעאָס מיט זיבן בילד־שטאַפּלען און זעקס ווידעאָ־שטאַפּלען. בײַשפּילן, אַנדרויד־אַפּס, אַודיאָ און טעקסט.',
    hero: ['קלײַבט אויס וואָס איר ווילט זען אָנליין.', 'Browslium העלפֿט פֿילטערן בילדער און ווידעאָס לויט דעם שטאַפּל וואָס איר קלײַבט אויס. זעט דעם חילוק אין קלאָרע בײַשפּילן.', 'זען בילד־שטאַפּלען', 'זען ווידעאָ־שטאַפּלען'],
    heroVisual: ['דאָס אָריגינעלע בילד', 'מיט אַ פֿילטער', 'אײַער אויסוואַל, אַ קלאָרער בליק'],
    imageEyebrow: 'בילד־פֿילטערונג', videoEyebrow: 'ווידעאָ־פֿילטערונג',
    imageLevels: ['ווייזן אָריגינעל', 'קענטיקע שטריכן', 'פֿרויען', 'פֿרויען און קליידער', 'פֿרויען און פֿאָרעם', 'קליידער און פֿאָרעם', 'בלאָקירן: פֿרויען', 'בלאָקירן: קליידער'],
    videoLevels: ['ווייזן אָריגינעל', 'פֿרויען', 'פֿרויען און קליידער', 'פֿרויען און פֿאָרעם', 'קליידער און פֿאָרעם', 'בלאָקירן: פֿרויען', 'בלאָקירן: קליידער'],
    levelGuide: 'קלײַבט אַ שטאַפּל כּדי צו זען וואָס ענדערט זיך.', sceneGuide: 'קלײַבט אַ בײַשפּיל',
    compareHint: 'שלעפּט די ליניע צו פֿאַרגלײַכן דאָס אָריגינעלע מיטן געפֿילטערטן בילד.',
    afterImages: 'ווײַטער צו ווידעאָ', afterVideos: 'לייענען וועגן אַודיאָ און טעקסט',
    audio: ['פֿילטערונג גייט ווײַטער ווי בילדער', 'אַודיאָ און טעקסט דאַרפֿן באַזונדערע אַנאַליזן. Browslium אַנטוויקלט אופֿנים צו נוצן אויסגעקליבענע כּללים פֿאַר געשטיצטע רייד און געשריבן אינהאַלט.', 'אַודיאָ', 'אַנאַליז פֿון געשטיצטן קלאַנג לויט צוגעפּאַסטע כּללים.', 'טעקסט', 'אַנאַליז פֿון געשטיצטן געשריבן אינהאַלט.', 'זען פֿילטערונג אויף אַנדרויד'],
    android: ['בילדער אין אַנדרויד־אַפּס זענען אויך וויכטיק', 'מען זעט אינהאַלט סײַ אין אַפּס סײַ אין בלעטערערס. Browslium ווערט אַנטוויקלט כּדי צו אָפּשאַצן געשטיצטע בילדער אין אַנדרויד־אַפּס לויטן אויסגעקליבענעם שטאַפּל.', 'אינהאַלט אין אַפּס', 'זיבן בילד־שטאַפּלען', 'אַ באַזונדערער בליק אויף יעדן טייל', 'זען דעוויסעס'],
    platforms: ['פֿאַר די דעוויסעס וואָס איר נוצט', 'Browslium ווערט אַנטוויקלט פֿאַר די הויפּט־פּלאַטפֿאָרמעס. פֿונקציעס ווענדן זיך אָן אין דעם דעוויס.', [['Android', 'פֿילטערונג פֿאַר געשטיצטן אינהאַלט אין אַפּס.'], ['iOS', 'אַ צוגאַנג פֿאַר iPhone און iPad.'], ['macOS', 'פֿילטערונג פֿאַר Mac.'], ['Windows', 'פֿילטערונג פֿאַר Windows־דעוויסעס.']], 'פֿאַר וועמען איז עס'],
    audiences: ['אַ פֿילטער לויט אײַערע באַדערפֿענישן', 'צי דאָס איז אײַער אייגענער דעוויס צי אַ געמיינזאַמער, איר קענט אויסקלײַבן דעם פּאַסיקן שטאַפּל.', ['פֿאַר זיך', 'פֿאַר דער משפּחה', 'פֿאַר לערנ־ערטער', 'פֿאַר דער קהילה'], 'אָפֿט געשטעלטע פֿראַגעס'],
    faqIntro: 'ענטפֿערס וועגן דעם וואָס Browslium פֿילטערט, ווי די שטאַפּלען אַרבעטן און פֿאַר וועלכע פּלאַטפֿאָרמעס מען אַנטוויקלט עס.',
    donate: ['העלפֿט אָנהאַלטן Browslium', 'אײַער בײַשטײַער העלפֿט אונטערהאַלטן די מענטשן און אינפֿראַסטרוקטור הינטערן פֿילטער.', 'שטיצן Browslium'],
    slogan: 'Intelligent Protection for Safer Browsing',
  },
  he: {
    metaTitle: 'סינון תמונות וסרטונים לפי הבחירה שלך | Browslium',
    metaDescription: 'ראו כיצד Browslium מסנן תמונות וסרטונים באמצעות שבע רמות לתמונות ושש רמות לווידאו. דוגמאות, סינון באפליקציות Android ותוכניות לשמע ולטקסט.',
    hero: ['לבחור מה לראות ברשת.', 'Browslium עוזר לסנן תמונות וסרטונים לפי הרמה שבחרת. אפשר לראות את ההבדל בדוגמאות פשוטות.', 'לראות רמות לתמונות', 'לראות רמות לווידאו'],
    heroVisual: ['התמונה המקורית', 'עם סינון', 'הבחירה שלך, תצוגה ברורה יותר'],
    imageEyebrow: 'סינון תמונות', videoEyebrow: 'סינון וידאו',
    imageLevels: ['להציג מקור', 'מאפיינים גלויים', 'נשים', 'נשים ובגדי נשים', 'נשים ושינוי צורה', 'בגדים ושינוי צורה', 'חסימה: נשים', 'חסימה: בגדים'],
    videoLevels: ['להציג מקור', 'נשים', 'נשים ובגדי נשים', 'נשים ושינוי צורה', 'בגדים ושינוי צורה', 'חסימה: נשים', 'חסימה: בגדים'],
    levelGuide: 'בחרו רמה כדי לראות מה משתנה.', sceneGuide: 'בחרו דוגמה',
    compareHint: 'גררו את הקו כדי להשוות בין התמונה המקורית לתמונה המסוננת.',
    afterImages: 'להמשיך לווידאו', afterVideos: 'לקרוא על שמע וטקסט',
    audio: ['הסינון לא נעצר בתמונות', 'שמע וטקסט דורשים ניתוח נפרד. Browslium מפתחת דרכים להחיל את המדיניות שנבחרה על תוכן מדובר וכתוב שנתמך.', 'שמע', 'ניתוח שמע נתמך לפי כללים המתאימים לקול.', 'טקסט', 'ניתוח טקסט נתמך לפי כללים המתאימים למילים.', 'לראות סינון ב־Android'],
    android: ['גם תמונות בתוך אפליקציות Android חשובות', 'אנחנו רואים תוכן באפליקציות, לא רק בדפדפן. Browslium מפותחת כדי לבחון תמונות נתמכות בתוך אפליקציות Android ולהחיל עליהן את הרמה שנבחרה.', 'תוכן בתוך אפליקציות', 'שבע רמות סינון לתמונות', 'התייחסות לפריט שמופיע מולך', 'לראות מכשירים'],
    platforms: ['למכשירים שבהם משתמשים כל יום', 'Browslium מפותחת לפלטפורמות מרכזיות. החוויה והתכונות הנתמכות תלויות במכשיר.', [['Android', 'סינון המיועד לתוכן נתמך בתוך אפליקציות.'], ['iOS', 'חוויה המיועדת ל־iPhone ול־iPad.'], ['macOS', 'סינון המיועד למחשבי Mac.'], ['Windows', 'סינון המיועד למחשבי Windows.']], 'למי זה מתאים'],
    audiences: ['סינון לפי מה שמתאים לך', 'במכשיר אישי או משותף, אפשר לבחור את הרמה שמתאימה למה שתרצה לראות.', ['לעצמך', 'למשפחה', 'למסגרות לימוד', 'לקהילה'], 'לקרוא שאלות נפוצות'],
    faqIntro: 'תשובות על מה ש־Browslium מסננת, איך הרמות פועלות ולאילו פלטפורמות היא מפותחת.',
    donate: ['עזרו לתחזק את Browslium', 'התרומה שלכם מסייעת להחזיק את הצוות והתשתית שמאחורי המסנן.', 'תמיכה ב־Browslium'],
    slogan: 'Intelligent Protection for Safer Browsing',
  },
  'pt-BR': {
    metaTitle: 'Filtre imagens e vídeos do seu jeito | Browslium',
    metaDescription: 'Veja como o Browslium filtra imagens e vídeos com sete níveis para imagens e seis para vídeos. Explore exemplos, apps Android e os planos para áudio e texto.',
    hero: ['Escolha o que você quer ver na internet.', 'O Browslium ajuda a filtrar imagens e vídeos de acordo com o nível que você escolher. Veja a diferença em exemplos simples.', 'Explorar níveis de imagem', 'Ver níveis de vídeo'],
    heroVisual: ['Imagem original', 'Com filtro', 'Sua escolha, uma visão mais clara'],
    imageEyebrow: 'Filtro de imagens', videoEyebrow: 'Filtro de vídeos',
    imageLevels: ['Ver original', 'Traços visíveis', 'Mulheres', 'Mulheres e roupas', 'Mulheres e forma', 'Roupas e forma', 'Bloquear: mulheres', 'Bloquear: roupas'],
    videoLevels: ['Ver original', 'Mulheres', 'Mulheres e roupas', 'Mulheres e forma', 'Roupas e forma', 'Bloquear: mulheres', 'Bloquear: roupas'],
    levelGuide: 'Escolha um nível para ver o que muda.', sceneGuide: 'Escolha um exemplo',
    compareHint: 'Arraste a linha para comparar a imagem original com a filtrada.',
    afterImages: 'Continuar para vídeos', afterVideos: 'Conhecer áudio e texto',
    audio: ['O filtro vai além das imagens', 'Áudio e texto precisam de análises próprias. O Browslium está desenvolvendo formas de aplicar as regras escolhidas a conteúdo falado e escrito compatível.', 'Áudio', 'Análise de áudio compatível com regras adequadas ao som.', 'Texto', 'Análise de texto compatível com regras adequadas às palavras.', 'Ver o filtro no Android'],
    android: ['Imagens dentro dos apps Android também importam', 'Vemos conteúdo tanto em aplicativos quanto no navegador. O Browslium está sendo desenvolvido para avaliar imagens compatíveis dentro de apps Android e aplicar o nível escolhido.', 'Conteúdo dentro dos apps', 'Sete níveis para imagens', 'Atenção ao item que você vê', 'Explorar dispositivos'],
    platforms: ['Para os dispositivos do dia a dia', 'O Browslium está sendo desenvolvido para as principais plataformas. A experiência e os recursos compatíveis dependem do dispositivo.', [['Android', 'Filtro pensado para conteúdo compatível dentro de apps.'], ['iOS', 'Uma experiência para iPhone e iPad.'], ['macOS', 'Filtro pensado para Mac.'], ['Windows', 'Filtro pensado para computadores Windows.']], 'Ver para quem é'],
    audiences: ['Um filtro que respeita suas escolhas', 'Em um dispositivo só seu ou compartilhado, escolha o nível de acordo com o que você quer ver.', ['Para você', 'Para sua família', 'Para espaços de ensino', 'Para sua comunidade'], 'Perguntas frequentes'],
    faqIntro: 'Respostas sobre o que o Browslium filtra, como funcionam os níveis e para quais plataformas ele está sendo desenvolvido.',
    donate: ['Ajude a manter o Browslium', 'Sua contribuição ajuda a manter a equipe e a infraestrutura por trás do filtro.', 'Apoiar o Browslium'],
    slogan: 'Intelligent Protection for Safer Browsing',
  },
  fr: {
    metaTitle: 'Filtrez les images et les vidéos selon vos choix | Browslium',
    metaDescription: 'Découvrez le filtrage des images et vidéos de Browslium : sept niveaux pour les images, six pour les vidéos, des exemples, Android, l’audio et le texte.',
    hero: ['Choisissez ce que vous voyez en ligne.', 'Browslium vous aide à filtrer les images et les vidéos selon le niveau que vous choisissez. Découvrez la différence avec des exemples concrets.', 'Explorer les niveaux d’image', 'Voir les niveaux vidéo'],
    heroVisual: ['Image d’origine', 'Avec filtrage', 'Votre choix, une vue plus claire'],
    imageEyebrow: 'Filtrage des images', videoEyebrow: 'Filtrage des vidéos',
    imageLevels: ['Voir l’original', 'Traits visibles', 'Femmes', 'Femmes et vêtements', 'Femmes et forme', 'Vêtements et forme', 'Bloquer : femmes', 'Bloquer : vêtements'],
    videoLevels: ['Voir l’original', 'Femmes', 'Femmes et vêtements', 'Femmes et forme', 'Vêtements et forme', 'Bloquer : femmes', 'Bloquer : vêtements'],
    levelGuide: 'Choisissez un niveau pour voir ce qui change.', sceneGuide: 'Choisissez un exemple',
    compareHint: 'Faites glisser la ligne pour comparer l’image d’origine et l’image filtrée.',
    afterImages: 'Passer aux vidéos', afterVideos: 'Découvrir l’audio et le texte',
    audio: ['Le filtrage va au-delà des images', 'L’audio et le texte demandent une analyse adaptée. Browslium développe des moyens d’appliquer les règles choisies aux contenus parlés et écrits pris en charge.', 'Audio', 'Analyse des contenus audio pris en charge avec des règles adaptées au son.', 'Texte', 'Analyse des textes pris en charge avec des règles adaptées aux mots.', 'Voir le filtrage sur Android'],
    android: ['Les images dans les applications Android comptent aussi', 'On voit des contenus dans les applications comme dans le navigateur. Browslium est conçu pour évaluer les images prises en charge dans les applications Android selon le niveau choisi.', 'Contenus dans les applications', 'Sept niveaux pour les images', 'Chaque élément peut être traité', 'Explorer les appareils'],
    platforms: ['Pour vos appareils du quotidien', 'Browslium est développé pour les grandes plateformes. L’expérience et les fonctions prises en charge dépendent de l’appareil.', [['Android', 'Un filtrage conçu pour les contenus pris en charge dans les applications.'], ['iOS', 'Une expérience pensée pour iPhone et iPad.'], ['macOS', 'Un filtrage conçu pour Mac.'], ['Windows', 'Un filtrage conçu pour les appareils Windows.']], 'À qui cela s’adresse'],
    audiences: ['Un filtre selon vos préférences', 'Sur un appareil personnel ou partagé, choisissez le niveau qui correspond à ce que vous souhaitez voir.', ['Pour vous', 'Pour votre famille', 'Pour les lieux d’apprentissage', 'Pour votre communauté'], 'Lire la FAQ'],
    faqIntro: 'Des réponses sur ce que filtre Browslium, le fonctionnement des niveaux et les plateformes concernées.',
    donate: ['Aidez à maintenir Browslium', 'Votre contribution soutient l’équipe et l’infrastructure nécessaires au filtre.', 'Soutenir Browslium'],
    slogan: 'Intelligent Protection for Safer Browsing',
  },
};
