// Human-facing explanations of the owner's policy definitions. These pages
// describe design intent and verified development status, not a live service.
export const explainers = {
  en: {
    image: {
      title: 'Image content filtering: seven policy levels | Browslium',
      description: 'Explore seven image-filtering policies with three real photo comparisons from controlled tests, and learn how Browslium is being developed.',
      h1: 'Image filtering that looks at the image',
      lead: 'A permitted page can still contain an image that does not match someone’s chosen standard. Browslium is being built to evaluate supported images individually and apply the selected image policy.',
      whyH: 'Why a website address is not enough',
      whyP: 'A domain or URL says where content comes from, but it does not describe every image on a page. Where a platform supports it, an image-level decision can affect one item without automatically making the same decision for the whole page.',
      processH: 'From image to policy decision',
      processP: 'A supported image enters the filtering path, is analyzed, and is compared with the chosen policy. The policy determines whether the item is shown, masked, altered or blocked. Exact handling and coverage depend on the platform and current implementation.',
      levelsH: 'The seven image policy levels',
      levelsP: 'These are the project’s current policy definitions. A listed policy is not a claim that it is available in a released product.',
      statusH: 'Current availability',
      statusP: 'Browslium remains in development and testing. The Android pilot does not yet run production AI filtering; Apple and Windows builds also require release work. Check the platform status before assuming an image policy is active on a device.',
    },
    video: {
      title: 'Video content filtering: six policy levels | Browslium',
      description: 'Watch controlled examples of Browslium’s six video-filtering policies across three clips, with original and filtered views and current development limits.',
      h1: 'Video filtering follows what changes over time',
      lead: 'A video is more than its page address or thumbnail. Browslium is being designed to evaluate supported moving content over time using a separate video policy.',
      whyH: 'Why video needs its own policy',
      whyP: 'Scenes and subjects change from frame to frame. A decision based only on a URL or a single still image can miss what appears later. Browslium therefore defines six video policies separately from its seven image policies.',
      processH: 'How the design handles video',
      processP: 'The intended filtering path analyzes supported video content across time, compares detections with the selected level, and applies the corresponding treatment. Actual coverage, timing and behavior depend on the platform and implementation stage.',
      levelsH: 'The six video policy levels',
      levelsP: 'The descriptions below come from the project’s current policy document. They describe intended behavior, not general production availability.',
      statusH: 'Current availability',
      statusP: 'Video filtering is still under development and testing. These clips document illustrative project tests; they do not demonstrate universal app coverage or a released filtering service.',
    },
    ui: {
      imageLabel: 'Image content filtering', videoLabel: 'Video content filtering',
      testsH: 'See examples from project tests',
      testsP: 'These short clips show masking in controlled tests. They are illustrative footage, not a live product demo or a guarantee of current device coverage.',
      clip1: 'Controlled test: a selected person is covered in a short video.',
      clip2: 'Controlled test: selected people are covered while the scene remains visible.',
      relatedH: 'Explore the full picture',
      relatedP: 'Compare the other media policy, try the interactive levels and read the current platform status.',
      statusLink: 'Platform status', levelsLink: 'Explore interactive levels', imageLink: 'Image filtering', videoLink: 'Video filtering',
    },
  },
  es: {
    image: {
      title: 'Filtrado de imágenes: siete niveles de protección | Browslium',
      description: 'Compara tres fotos originales con los resultados de siete niveles de filtrado de imágenes en pruebas controladas de Browslium.',
      h1: 'Filtrado de imágenes según su contenido',
      lead: 'Una página permitida puede incluir una imagen que no se ajuste a la política elegida. Browslium se desarrolla para evaluar imágenes compatibles por separado y aplicarles el nivel seleccionado.',
      whyH: 'La dirección de una página no cuenta toda la historia',
      whyP: 'El dominio indica de dónde viene el contenido, pero no describe cada imagen. Donde la plataforma lo permita, una decisión sobre una imagen podrá afectar solo a ese elemento, sin imponerla automáticamente a toda la página.',
      processH: 'De la imagen a la decisión',
      processP: 'Una imagen compatible entra en el proceso de filtrado, se analiza y se compara con la política elegida. Según el nivel, puede mostrarse, cubrirse, modificarse o bloquearse. El tratamiento concreto depende de la plataforma y de la implementación actual.',
      levelsH: 'Los siete niveles de filtrado de imágenes',
      levelsP: 'Estas son las definiciones vigentes del proyecto. Que un nivel esté definido no significa que ya esté disponible en un producto lanzado.',
      statusH: 'Disponibilidad actual',
      statusP: 'Browslium sigue en desarrollo y pruebas. El piloto de Android todavía no ejecuta filtrado con IA en producción; las versiones de Apple y Windows también tienen tareas pendientes antes del lanzamiento. Consulta el estado de cada plataforma.',
    },
    video: {
      title: 'Filtrado de video: seis niveles de protección | Browslium',
      description: 'Mira tres vídeos originales y sus resultados en los seis niveles de filtrado de Browslium, con ejemplos de pruebas controladas.',
      h1: 'Filtrado de video a lo largo del tiempo',
      lead: 'Un video es más que la dirección de su página o una miniatura. Browslium se diseña para evaluar el contenido compatible mientras cambia, mediante una política propia para video.',
      whyH: 'El video necesita reglas distintas',
      whyP: 'Las escenas y las personas cambian entre fotogramas. Decidir solo por la URL o por una imagen fija puede pasar por alto lo que aparece después. Por eso el proyecto define seis niveles de video, independientes de los siete de imagen.',
      processH: 'Cómo está diseñado el análisis de video',
      processP: 'El proceso previsto examina el contenido compatible a lo largo del tiempo, compara lo detectado con el nivel elegido y aplica el tratamiento correspondiente. La cobertura y el comportamiento reales dependen de la plataforma y la fase de implementación.',
      levelsH: 'Los seis niveles de filtrado de video',
      levelsP: 'Las descripciones proceden del documento de políticas vigente. Explican lo previsto; no afirman disponibilidad general en producción.',
      statusH: 'Disponibilidad actual',
      statusP: 'El filtrado de video continúa en desarrollo y pruebas. Estos clips son ejemplos de pruebas del proyecto; no demuestran compatibilidad universal con aplicaciones ni un servicio ya lanzado.',
    },
    ui: {
      imageLabel: 'Filtrado de imágenes', videoLabel: 'Filtrado de video',
      testsH: 'Ejemplos de pruebas del proyecto',
      testsP: 'Estos clips breves muestran coberturas en pruebas controladas. Son material ilustrativo, no una demo en vivo ni una garantía de compatibilidad actual.',
      clip1: 'Prueba controlada: se cubre a una persona seleccionada en un video corto.',
      clip2: 'Prueba controlada: se cubre a personas seleccionadas y el resto de la escena permanece visible.',
      relatedH: 'Sigue explorando',
      relatedP: 'Compara la otra política, prueba los niveles interactivos y consulta el estado por plataforma.',
      statusLink: 'Estado de las plataformas', levelsLink: 'Explorar los niveles', imageLink: 'Filtrado de imágenes', videoLink: 'Filtrado de video',
    },
  },
  ru: {
    image: {
      title: 'Фильтрация изображений: семь уровней | Browslium',
      description: 'Сравните три исходных фото с результатами семи уровней фильтрации изображений Browslium в контролируемых тестах.',
      h1: 'Фильтрация содержимого изображений',
      lead: 'На разрешённом сайте могут быть изображения, которые не соответствуют выбранным правилам. Browslium разрабатывается для отдельной проверки поддерживаемых изображений.',
      whyH: 'Адрес сайта не описывает каждую картинку',
      whyP: 'Домен показывает источник страницы, но не всё её содержимое. Там, где платформа это поддерживает, решение по одному изображению не обязательно должно распространяться на всю страницу.',
      processH: 'От изображения к решению',
      processP: 'Поддерживаемое изображение поступает на анализ и сравнивается с выбранной политикой. В зависимости от уровня его можно показать, скрыть часть, изменить или заблокировать. Точное поведение зависит от платформы и стадии разработки.',
      levelsH: 'Семь уровней фильтрации изображений',
      levelsP: 'Это действующие определения политик проекта. Наличие уровня в списке не означает, что он уже доступен пользователям.',
      statusH: 'Что доступно сейчас',
      statusP: 'Browslium находится в разработке и тестировании. В пилотной версии Android промышленная фильтрация с ИИ пока не работает; версии для Apple и Windows также требуют подготовки к выпуску. Сверяйтесь со статусом платформ.',
    },
    video: {
      title: 'Фильтрация видео: шесть уровней | Browslium',
      description: 'Посмотрите три исходных ролика и результаты шести уровней фильтрации видео Browslium на примерах контролируемых тестов.',
      h1: 'Фильтрация видеоконтента по мере его изменения',
      lead: 'Видео нельзя описать только адресом страницы или обложкой. Browslium разрабатывается для анализа поддерживаемого видеоконтента во времени по отдельной политике.',
      whyH: 'Почему для видео нужны свои правила',
      whyP: 'Сцены и объекты меняются от кадра к кадру. Проверка одного адреса или стоп-кадра может пропустить то, что появится позже. Поэтому для видео предусмотрены шесть уровней, отличных от семи уровней изображений.',
      processH: 'Как задуман анализ видео',
      processP: 'Предусмотрено исследование поддерживаемого видео во времени, сопоставление обнаруженного с выбранным уровнем и применение соответствующего действия. Реальное покрытие и поведение зависят от платформы и готовности компонентов.',
      levelsH: 'Шесть уровней фильтрации видео',
      levelsP: 'Ниже приведены определения из актуального документа проекта. Это описание замысла, а не заявление о доступности в готовом сервисе.',
      statusH: 'Что доступно сейчас',
      statusP: 'Фильтрация видео ещё разрабатывается и тестируется. Ролики показывают отдельные испытания проекта; они не подтверждают поддержку всех приложений или выпуск сервиса.',
    },
    ui: {
      imageLabel: 'Фильтрация изображений', videoLabel: 'Фильтрация видео',
      testsH: 'Примеры испытаний проекта',
      testsP: 'Короткие ролики показывают маскировку в контролируемых испытаниях. Это иллюстрация, а не работающий сервис для всех устройств.',
      clip1: 'Контролируемое испытание: выбранный человек закрыт маской в коротком ролике.',
      clip2: 'Контролируемое испытание: выбранные люди скрыты, остальная сцена видна.',
      relatedH: 'Узнать больше',
      relatedP: 'Сравните другую политику, изучите уровни и проверьте статус платформ.',
      statusLink: 'Статус платформ', levelsLink: 'Изучить уровни', imageLink: 'Фильтрация изображений', videoLink: 'Фильтрация видео',
    },
  },
  he: {
    image: {
      title: 'סינון תמונות: שבע רמות סינון | Browslium',
      description: 'השוו שלוש תמונות מקור לתוצאות של שבע רמות סינון תמונות בבדיקות מבוקרות של Browslium.',
      h1: 'סינון תמונות לפי התוכן שלהן',
      lead: 'גם אתר שמותר לגלוש בו עשוי להכיל תמונה שאינה מתאימה למדיניות שנבחרה. Browslium נמצאת בפיתוח כדי לבדוק תמונות נתמכות בנפרד ולהחיל עליהן את רמת הסינון הרצויה.',
      whyH: 'כתובת האתר לא מספרת הכול',
      whyP: 'הדומיין מציין מאין הגיע הדף, אך לא מתאר כל תמונה שמופיעה בו. בפלטפורמות שיתמכו בכך, החלטה לגבי תמונה אחת לא תחייב אוטומטית חסימה של הדף כולו.',
      processH: 'מהתמונה להחלטת הסינון',
      processP: 'תמונה נתמכת עוברת לניתוח ונבדקת מול המדיניות שנבחרה. בהתאם לרמה, אפשר להציג אותה, להסתיר חלק ממנה, לשנות אותה או לחסום אותה. אופן הטיפול בפועל תלוי בפלטפורמה ובמצב הפיתוח.',
      levelsH: 'שבע רמות סינון התמונות',
      levelsP: 'אלה הגדרות המדיניות העדכניות של הפרויקט. הופעת רמה ברשימה אינה מעידה שהיא כבר זמינה במוצר שהושק.',
      statusH: 'זמינות נוכחית',
      statusP: 'Browslium עדיין בפיתוח ובבדיקות. בפיילוט של Android סינון ה-AI עדיין אינו פעיל בייצור; גם גרסאות Apple ו-Windows דורשות עבודה נוספת לפני השקה. כדאי לבדוק את מצב הפלטפורמות.',
    },
    video: {
      title: 'סינון סרטונים: שש רמות סינון | Browslium',
      description: 'צפו בשלושה סרטוני מקור ובתוצאות של שש רמות סינון וידאו של Browslium מתוך בדיקות מבוקרות.',
      h1: 'סינון סרטונים לאורך זמן',
      lead: 'סרטון הוא יותר מכתובת הדף או מהתמונה הממוזערת שלו. Browslium מתוכננת לנתח תוכן וידאו נתמך תוך כדי שינויו, באמצעות מדיניות נפרדת לסרטונים.',
      whyH: 'למה סרטון דורש כללים משלו',
      whyP: 'הסצנות והדמויות משתנות מפריים לפריים. בדיקה של כתובת או תמונה אחת בלבד עלולה להחמיץ תוכן שמופיע בהמשך. לכן הוגדרו לסרטונים שש רמות, בנפרד משבע רמות התמונות.',
      processH: 'כיצד מתוכנן ניתוח הווידאו',
      processP: 'המערכת מיועדת לנתח וידאו נתמך לאורך זמן, להשוות את הממצאים לרמה שנבחרה ולהחיל את הטיפול המתאים. הכיסוי וההתנהגות בפועל תלויים בפלטפורמה ובשלב הפיתוח.',
      levelsH: 'שש רמות סינון הסרטונים',
      levelsP: 'ההגדרות שלהלן מבוססות על מסמך המדיניות העדכני של הפרויקט. הן מתארות את היעד, ולא זמינות כללית של שירות פעיל.',
      statusH: 'זמינות נוכחית',
      statusP: 'סינון סרטונים נמצא עדיין בפיתוח ובבדיקות. הסרטונים כאן מתעדים ניסויים נקודתיים בפרויקט; הם אינם מוכיחים תמיכה בכל אפליקציה או שירות שהושק.',
    },
    ui: {
      imageLabel: 'סינון תמונות', videoLabel: 'סינון סרטונים',
      testsH: 'דוגמאות מבדיקות הפרויקט',
      testsP: 'הסרטונים הקצרים מציגים הסתרה בבדיקות מבוקרות. אלה דוגמאות להמחשה, ולא הדגמה חיה של מוצר זמין או הבטחה לתמיכה במכשירים.',
      clip1: 'בדיקה מבוקרת: אדם שנבחר מוסתר בסרטון קצר.',
      clip2: 'בדיקה מבוקרת: אנשים שנבחרו מוסתרים, ושאר הסצנה נותרת גלויה.',
      relatedH: 'להמשך העיון',
      relatedP: 'אפשר להשוות למדיניות הנוספת, להתנסות ברמות הסינון ולבדוק את מצב הפלטפורמות.',
      statusLink: 'מצב הפלטפורמות', levelsLink: 'לרמות הסינון', imageLink: 'סינון תמונות', videoLink: 'סינון סרטונים',
    },
  },
  yi: {
    image: {
      title: 'בילדער־פֿילטערונג: זיבן שטאַפּלען | Browslium',
      description: 'פֿאַרגלײַכט דרײַ אָריגינעלע פֿאָטאָס מיט די רעזולטאַטן פֿון זיבן בילד־פֿילטער־ניוואָען אין קאָנטראָלירטע Browslium־פּרוּוון.',
      h1: 'בילדער פֿילטערן לויט זייער אינהאַלט',
      lead: 'אויף אַ דערלויבטער וועבזײַט קען זיך געפֿינען אַ בילד וואָס פּאַסט נישט צו דער אויסגעקליבענער פּאָליטיק. Browslium ווערט אַנטוויקלט כּדי צו קאָנטראָלירן געשטיצטע בילדער באַזונדער.',
      whyH: 'דער וועב־אַדרעס דערציילט נישט אַלץ',
      whyP: 'אַ דאָמיין ווײַזט פֿון וואַנען אַ זײַט קומט, אָבער נישט וואָס עס געפֿינט זיך אין יעדן בילד. וווּ די פּלאַטפאָרמע שטיצט עס, דאַרף אַ באַשלוס וועגן איין בילד נישט אויטאָמאַטיש פֿאַרמאַכן די גאַנצע זײַט.',
      processH: 'פֿונעם בילד ביזן באַשלוס',
      processP: 'אַ געשטיצטער בילד גייט אַרײַן אין אַן אַנאַליז און ווערט פֿאַרגליכן מיט דער אויסגעקליבענער פּאָליטיק. לויטן שטאַפּל קען מען עס ווײַזן, פֿאַרדעקן, פֿאַרענדערן אָדער בלאָקירן. דער גענויער אופֿן הענגט אָפּ פֿון דער פּלאַטפאָרמע און אַנטוויקלונג.',
      levelsH: 'די זיבן שטאַפּלען פֿאַר בילדער',
      levelsP: 'דאָס זענען די איצטיקע פּאָליטיק־באַשרײַבונגען פֿונעם פּראָיעקט. אַ באַשריבענער שטאַפּל מיינט נישט אַז ער איז שוין פֿאַראַן אין אַ אַרויסגעגעבן פּראָדוקט.',
      statusH: 'וואָס איז איצט פֿאַראַן',
      statusP: 'Browslium איז נאָך אין אַנטוויקלונג און פּרוּוון. אינעם Android־פּילאָט אַרבעט די AI־פֿילטערונג נאָך נישט אין פּראָדוקציע; די Apple־ און Windows־ווערסיעס דאַרפֿן אויך נאָך אַרבעט פֿאַרן אַרויסגעבן. זעט דעם פּלאַטפאָרמע־סטאַטוס.',
    },
    video: {
      title: 'ווידעאָ־פֿילטערונג: זעקס שטאַפּלען | Browslium',
      description: 'זעט דרײַ אָריגינעלע קליפּס און די רעזולטאַטן פֿון זעקס ווידעאָ־פֿילטער־ניוואָען אין קאָנטראָלירטע Browslium־פּרוּוון.',
      h1: 'ווידעאָס פֿילטערן בשעת דער אינהאַלט ענדערט זיך',
      lead: 'אַ ווידעאָ איז מער ווי זײַן וועב־אַדרעס אָדער פֿאָרויסבילד. Browslium ווערט אַנטוויקלט צו קאָנטראָלירן געשטיצטן באַוועגלעכן אינהאַלט איבער דער צײַט, מיט אַן אייגענער ווידעאָ־פּאָליטיק.',
      whyH: 'פֿאַר וואָס ווידעאָ דאַרף באַזונדערע כּללים',
      whyP: 'סצענעס און מענטשן ענדערן זיך פֿון איין בילד צום צווייטן. אַ קאָנטראָל פֿון בלויז דעם אַדרעס אָדער איין ראַם קען פֿאַרפֿעלן וואָס קומט שפּעטער. דעריבער האָט דער פּראָיעקט זעקס ווידעאָ־שטאַפּלען, באַזונדער פֿון די זיבן בילדער־שטאַפּלען.',
      processH: 'ווי דער ווידעאָ־אַנאַליז איז אויסגעטראַכט',
      processP: 'דער פּלאַן איז צו אַנאַליזירן געשטיצטן ווידעאָ איבער דער צײַט, פֿאַרגלײַכן די דערקענונגען מיטן אויסגעקליבענעם שטאַפּל און אָנווענדן די פּאַסיקע באַהאַנדלונג. וואָס טאַקע אַרבעט הענגט אָפּ פֿון דער פּלאַטפאָרמע און דער אַנטוויקלונג.',
      levelsH: 'די זעקס שטאַפּלען פֿאַר ווידעאָס',
      levelsP: 'די דאָזיקע באַשרײַבונגען שטאַמען פֿונעם איצטיקן פּאָליטיק־דאָקומענט. זיי באַשרײַבן דעם פּלאַן, נישט אַ שוין פֿאַרענדיקטן דינסט.',
      statusH: 'וואָס איז איצט פֿאַראַן',
      statusP: 'ווידעאָ־פֿילטערונג איז נאָך אין אַנטוויקלונג און פּרוּוון. די קליפּס ווײַזן באַגרענעצטע פּראָיעקט־פּרוּוון; זיי באַווײַזן נישט אַז דער דינסט אַרבעט שוין אין אַלע אַפּליקאַציעס.',
    },
    ui: {
      imageLabel: 'בילדער־פֿילטערונג', videoLabel: 'ווידעאָ־פֿילטערונג',
      testsH: 'בײַשפּילן פֿון פּראָיעקט־פּרוּוון',
      testsP: 'די קורצע קליפּס ווײַזן פֿאַרדעקונג אין קאָנטראָלירטע פּרוּוון. דאָס זענען בלויז בײַשפּילן, נישט קיין לעבעדיקע דעמאָ פֿון אַ פֿאַראַנענעם פּראָדוקט.',
      clip1: 'קאָנטראָלירטער פּרוּוו: אַן אויסגעקליבענער מענטש ווערט פֿאַרדעקט אין אַ קורצן ווידעאָ.',
      clip2: 'קאָנטראָלירטער פּרוּוו: אויסגעקליבענע מענטשן ווערן פֿאַרדעקט, און די איבעריקע סצענע בלײַבט זעבאַר.',
      relatedH: 'לייענט ווײַטער',
      relatedP: 'פֿאַרגלײַכט די אַנדערע פּאָליטיק, פּרוּווט די שטאַפּלען און זעט דעם פּלאַטפאָרמע־סטאַטוס.',
      statusLink: 'פּלאַטפאָרמע־סטאַטוס', levelsLink: 'זען די שטאַפּלען', imageLink: 'בילדער־פֿילטערונג', videoLink: 'ווידעאָ־פֿילטערונג',
    },
  },
  'pt-BR': {
    image: {
      title: 'Filtro de imagens: sete níveis de proteção | Browslium',
      description: 'Compare três fotos originais com os resultados dos sete níveis de filtro de imagens do Browslium em testes controlados.',
      h1: 'Filtro de imagens pelo que elas mostram',
      lead: 'Um site permitido também pode conter uma imagem que não combina com a política escolhida. O Browslium está sendo desenvolvido para avaliar imagens compatíveis individualmente.',
      whyH: 'O endereço do site não revela cada imagem',
      whyP: 'O domínio mostra de onde vem a página, mas não descreve todo o conteúdo dela. Onde houver suporte técnico, a decisão sobre uma imagem poderá afetar apenas aquele item, sem bloquear automaticamente a página inteira.',
      processH: 'Da imagem à decisão',
      processP: 'Uma imagem compatível entra no fluxo de análise e é comparada com a política selecionada. Conforme o nível, ela pode ser exibida, coberta, alterada ou bloqueada. O comportamento real depende da plataforma e do estágio da implementação.',
      levelsH: 'Os sete níveis do filtro de imagens',
      levelsP: 'Estas são as definições atuais do projeto. Um nível descrito aqui não significa que já esteja disponível em um produto lançado.',
      statusH: 'Disponibilidade atual',
      statusP: 'O Browslium segue em desenvolvimento e testes. O piloto Android ainda não executa filtragem com IA em produção; as versões Apple e Windows também precisam de trabalho antes do lançamento. Consulte o status das plataformas.',
    },
    video: {
      title: 'Filtro de vídeos: seis níveis de proteção | Browslium',
      description: 'Assista a três clipes originais e aos resultados dos seis níveis de filtro de vídeos do Browslium em testes controlados.',
      h1: 'Filtro de vídeos para conteúdo que muda',
      lead: 'Um vídeo é mais do que o endereço da página ou sua miniatura. O Browslium está sendo projetado para analisar conteúdo compatível ao longo do tempo com uma política específica para vídeos.',
      whyH: 'Por que vídeos precisam de regras próprias',
      whyP: 'Cenas e pessoas mudam de um quadro para outro. Uma decisão baseada só na URL ou em uma imagem parada pode deixar passar o que aparece depois. Por isso existem seis níveis para vídeos, separados dos sete níveis para imagens.',
      processH: 'Como a análise de vídeos foi planejada',
      processP: 'O fluxo previsto analisa vídeos compatíveis ao longo do tempo, compara o que foi detectado com o nível escolhido e aplica o tratamento correspondente. A cobertura e o funcionamento reais dependem da plataforma e do estágio de desenvolvimento.',
      levelsH: 'Os seis níveis do filtro de vídeos',
      levelsP: 'As definições abaixo vêm do documento atual do projeto. Elas descrevem a política planejada, não a disponibilidade geral em produção.',
      statusH: 'Disponibilidade atual',
      statusP: 'A filtragem de vídeos ainda está em desenvolvimento e testes. Estes clipes registram testes específicos do projeto; não comprovam suporte a todos os aplicativos nem um serviço já lançado.',
    },
    ui: {
      imageLabel: 'Filtro de imagens', videoLabel: 'Filtro de vídeos',
      testsH: 'Exemplos de testes do projeto',
      testsP: 'Os clipes curtos mostram a cobertura de pessoas em testes controlados. São exemplos ilustrativos, não uma demonstração ao vivo nem garantia de compatibilidade atual.',
      clip1: 'Teste controlado: uma pessoa selecionada é coberta em um vídeo curto.',
      clip2: 'Teste controlado: pessoas selecionadas são cobertas, enquanto o restante da cena permanece visível.',
      relatedH: 'Continue explorando',
      relatedP: 'Compare a outra política, experimente os níveis e confira o status de cada plataforma.',
      statusLink: 'Status das plataformas', levelsLink: 'Explorar os níveis', imageLink: 'Filtro de imagens', videoLink: 'Filtro de vídeos',
    },
  },
  fr: {
    image: {
      title: 'Filtrage des images : sept niveaux | Browslium',
      description: 'Comparez trois photos originales aux résultats des sept niveaux de filtrage d’images Browslium lors de tests contrôlés.',
      h1: 'Filtrer les images selon leur contenu',
      lead: 'Une page autorisée peut contenir une image qui ne correspond pas à la règle choisie. Browslium est en développement pour examiner séparément les images compatibles.',
      whyH: 'L’adresse du site ne décrit pas chaque image',
      whyP: 'Le domaine indique la provenance de la page, mais pas le contenu de toutes ses images. Lorsque la plateforme le permet, une décision concernant une image peut s’appliquer à cet élément sans bloquer automatiquement toute la page.',
      processH: 'De l’image à la décision',
      processP: 'Une image compatible entre dans le parcours d’analyse et est comparée à la règle choisie. Selon le niveau, elle peut être affichée, masquée, modifiée ou bloquée. Le fonctionnement réel dépend de la plateforme et de l’avancement du projet.',
      levelsH: 'Les sept niveaux de filtrage des images',
      levelsP: 'Voici les définitions actuelles du projet. La présence d’un niveau dans cette liste ne signifie pas qu’il soit déjà disponible dans un produit publié.',
      statusH: 'Disponibilité actuelle',
      statusP: 'Browslium est encore en développement et en test. Le pilote Android ne dispose pas encore d’un filtrage IA actif en production ; les versions Apple et Windows demandent aussi du travail avant leur sortie. Consultez l’état des plateformes.',
    },
    video: {
      title: 'Filtrage des vidéos : six niveaux | Browslium',
      description: 'Regardez trois extraits originaux et les résultats des six niveaux de filtrage vidéo Browslium issus de tests contrôlés.',
      h1: 'Filtrer les vidéos au fil des images',
      lead: 'Une vidéo ne se résume ni à l’adresse de sa page ni à sa miniature. Browslium est conçu pour examiner les contenus vidéo compatibles au fil du temps, avec des règles qui leur sont propres.',
      whyH: 'Pourquoi la vidéo demande ses propres règles',
      whyP: 'Les scènes et les personnes changent d’une image à l’autre. Une décision fondée uniquement sur l’URL ou une seule image fixe peut manquer ce qui apparaît ensuite. Le projet prévoit donc six niveaux vidéo, distincts des sept niveaux image.',
      processH: 'Comment l’analyse vidéo est envisagée',
      processP: 'Le parcours prévu analyse les vidéos compatibles dans le temps, compare les éléments repérés au niveau choisi et applique le traitement correspondant. La couverture et le comportement réels dépendent de la plateforme et de l’avancement technique.',
      levelsH: 'Les six niveaux de filtrage vidéo',
      levelsP: 'Ces définitions proviennent du document de référence actuel du projet. Elles décrivent des règles prévues, pas une disponibilité générale en production.',
      statusH: 'Disponibilité actuelle',
      statusP: 'Le filtrage vidéo est toujours en développement et en test. Ces extraits montrent des essais ponctuels du projet ; ils ne prouvent ni une couverture de toutes les applications ni un service déjà lancé.',
    },
    ui: {
      imageLabel: 'Filtrage des images', videoLabel: 'Filtrage des vidéos',
      testsH: 'Exemples issus des essais du projet',
      testsP: 'Ces courts extraits montrent un masquage lors d’essais contrôlés. Ils sont illustratifs : ce n’est pas une démonstration en direct ni une promesse de compatibilité actuelle.',
      clip1: 'Essai contrôlé : une personne sélectionnée est masquée dans une courte vidéo.',
      clip2: 'Essai contrôlé : des personnes sélectionnées sont masquées, le reste de la scène demeure visible.',
      relatedH: 'Pour aller plus loin',
      relatedP: 'Comparez l’autre règle, essayez les niveaux interactifs et consultez l’état des plateformes.',
      statusLink: 'État des plateformes', levelsLink: 'Explorer les niveaux', imageLink: 'Filtrage des images', videoLink: 'Filtrage des vidéos',
    },
  },
};
