// Every answer below is visible in the page's native HTML <details>.
// FAQPage JSON-LD is intentionally omitted because Google retired FAQ rich results.
export const faqs = {
  en: [
    ['What is Browslium?', 'Browslium is a content-filtering system in development. It is designed to analyze supported material reaching a user, including images, video, audio, text and documents, rather than relying only on whole-site decisions.'],
    ['How is Browslium different from a traditional internet filter?', 'Domain, URL, category and blocklist controls can be useful. Browslium aims to add analysis of supported items within a page or app according to the selected policy.'],
    ['Does Browslium only block websites?', 'No. Website and URL rules can be part of protection, but the design also evaluates supported individual items so a decision need not apply to an entire website.'],
    ['What types of content can Browslium filter?', 'The architecture covers supported images, video, audio, text, documents, downloads and web content. Exact availability depends on the platform, feature and development stage.'],
    ['What are filtering levels?', 'A filtering level is a set of rules for handling supported content. Different levels let a person or organization choose a policy that fits its needs.'],
    ['How many image-filtering levels are there?', 'The project defines seven image-filtering levels. The interactive section above explains each policy; current availability varies by platform and feature.'],
    ['How many video-filtering levels are there?', 'The project defines six video-filtering levels. Video has separate policies because moving content requires analysis over time.'],
    ['Why use several levels instead of one setting?', 'People and organizations have different standards. Several levels allow a more precise policy than a single on/off switch.'],
    ['How does image filtering work?', 'When a supported image passes through the filtering path, the system is designed to analyze it against the selected image policy and decide how to handle it. The preview above illustrates policies without using inappropriate imagery.'],
    ['How does video filtering work?', 'Browslium is designed to analyze supported video content over time and apply a video-specific policy. Processing moving frames differs from processing a still image; production capabilities remain feature-dependent.'],
    ['What if the system is uncertain about content?', 'Uncertainty is intended to be handled under the chosen safety policy. The response may involve further analysis or more conservative handling, depending on the content type and implementation; no universal production behavior is promised.'],
    ['Does Browslium also filter audio and text?', 'The architecture includes separate analysis and policy logic for supported audio and text. These capabilities are in development and their availability should be checked by platform.'],
    ['Will one item cause an entire page to be blocked?', 'Not necessarily. Where technically supported, the system is designed to distinguish an item from the page containing it so one decision need not determine the outcome for everything else.'],
    ['Does Browslium work in every app and browser?', 'No universal coverage is claimed. It depends on operating-system restrictions, app architecture and the Browslium components available on each platform.'],
    ['Which platforms are being developed?', 'Android, Apple platforms and Windows are in development or testing. See the Platform status section for the current status of each; none is presented here as a general production release.'],
    ['Will content filtering slow down my internet?', 'Analysis takes processing time. The design uses optimized pipelines and caching, but actual delay can vary by content, device, network and the analysis required; no fixed latency is promised.'],
    ['Is Browslium available today?', 'Browslium is in active development and testing. Availability differs by platform and feature; the Platform status section above is the current shared summary.'],
    ['Is Browslium only for parents?', 'No. It is being designed for individuals, families, schools, businesses, nonprofits and community organizations seeking more control over content on their devices.'],
    ['How much will Browslium cost?', 'The project’s goal is to make filtering accessible without charging users for access, supported by voluntary contributions. Final availability and pricing have not been announced.'],
    ['Why does Browslium ask for contributions?', 'Engineering, testing, AI infrastructure, GPU computing, servers, security and operation all have costs. Voluntary support helps fund the ongoing work.'],
    ['How are contributions processed?', 'Contributions use a Stripe-hosted payment page. Browslium’s website does not collect or store payment-card details. A contribution does not purchase a product or service.'],
    ['Can I contribute every month?', 'The current Stripe link accepts a one-time amount chosen by the contributor. A monthly option is not shown because recurring contributions have not been configured.'],
    ['How does Browslium handle privacy?', 'Filtering supported content requires analysis to make a decision. The current Privacy Policy explains this website and voluntary contributions. Product-specific data handling and retention details will be published before a general service release.'],
  ],
  es: [
    ['¿Qué es Browslium?', 'Browslium es un sistema de filtrado de contenido en desarrollo. Está diseñado para analizar material compatible que llega al usuario —imágenes, video, audio, texto y documentos—, además de las decisiones sobre sitios completos.'],
    ['¿En qué se diferencia de un filtro de internet tradicional?', 'Filtrar por dominio, URL, categoría o lista de bloqueo sigue siendo útil. Browslium busca añadir análisis de elementos compatibles dentro de una página o aplicación según la política elegida.'],
    ['¿Browslium solo bloquea páginas web?', 'No. Las reglas para sitios y URL pueden formar parte de la protección, pero el diseño también evalúa elementos individuales compatibles sin imponer siempre la misma decisión a todo el sitio.'],
    ['¿Qué contenido puede filtrar?', 'La arquitectura contempla imágenes, video, audio, texto, documentos, descargas y contenido web compatibles. La disponibilidad exacta depende de la plataforma, la función y la etapa de desarrollo.'],
    ['¿Qué son los niveles de filtrado?', 'Cada nivel reúne reglas para tratar contenido compatible. Así, una persona u organización puede elegir una política acorde con sus necesidades.'],
    ['¿Cuántos niveles hay para imágenes?', 'El proyecto define siete niveles de filtrado de imágenes. La sección interactiva explica cada política; la disponibilidad actual varía según la plataforma y la función.'],
    ['¿Cuántos niveles hay para video?', 'El proyecto define seis niveles de filtrado de video. El video requiere reglas propias porque su contenido cambia con el tiempo.'],
    ['¿Por qué hay varios niveles en lugar de un interruptor?', 'Las necesidades cambian de una persona u organización a otra. Varios niveles permiten una política más precisa que simplemente activar o desactivar un filtro.'],
    ['¿Cómo funciona el filtrado de imágenes?', 'Cuando una imagen compatible entra en el proceso de filtrado, el sistema está diseñado para analizarla según la política elegida y decidir cómo tratarla. La vista anterior ilustra las políticas sin imágenes inapropiadas.'],
    ['¿Cómo funciona el filtrado de video?', 'Browslium está diseñado para analizar video compatible a lo largo del tiempo y aplicar una política específica. Procesar escenas en movimiento es distinto a procesar una imagen fija; las funciones de producción dependen de cada implementación.'],
    ['¿Qué ocurre si el sistema no está seguro?', 'La incertidumbre debe tratarse según la política de seguridad elegida. Según el contenido y la implementación, puede requerirse más análisis o una respuesta más conservadora; no se promete una conducta única en producción.'],
    ['¿También filtra audio y texto?', 'La arquitectura incluye análisis y reglas propios para audio y texto compatibles. Estas funciones están en desarrollo y su disponibilidad depende de la plataforma.'],
    ['¿Una sola imagen puede bloquear toda la página?', 'No necesariamente. Cuando es técnicamente posible, el sistema distingue un elemento de la página que lo contiene para que una decisión no determine automáticamente el destino de todo lo demás.'],
    ['¿Funciona en todas las aplicaciones y navegadores?', 'No se afirma cobertura universal. Depende de las restricciones del sistema operativo, la arquitectura de cada app y los componentes de Browslium presentes en la plataforma.'],
    ['¿Para qué plataformas se está desarrollando?', 'El trabajo abarca Android, plataformas Apple y Windows. Consulta Estado por plataforma para ver la fase actual de cada una; aquí no se anuncia un lanzamiento general.'],
    ['¿El filtro hará más lenta mi conexión?', 'Analizar contenido requiere procesamiento. El diseño busca reducir demoras con procesos optimizados y caché, pero el tiempo real cambia según el contenido, dispositivo, red y análisis; no se promete una latencia fija.'],
    ['¿Browslium ya está disponible?', 'Browslium está en desarrollo y pruebas. La disponibilidad cambia según la plataforma y la función; la sección Estado por plataforma muestra el resumen actual.'],
    ['¿Es solo para padres?', 'No. Está pensado para personas, familias, escuelas, empresas, organizaciones sin fines de lucro y comunidades que buscan más control sobre el contenido de sus dispositivos.'],
    ['¿Cuánto costará Browslium?', 'La meta del proyecto es ofrecer acceso al filtrado sin cobrar a los usuarios, con apoyo de aportaciones voluntarias. El precio y la disponibilidad definitivos aún no se han anunciado.'],
    ['¿Por qué pide aportaciones?', 'La ingeniería, las pruebas, la infraestructura de IA, el cómputo GPU, los servidores, la seguridad y la operación tienen costos. El apoyo voluntario ayuda a financiar el trabajo continuo.'],
    ['¿Cómo se procesan las aportaciones?', 'Se hacen en una página de pago alojada por Stripe. Esta web no recoge ni guarda datos de tarjetas. Una aportación no compra un producto ni un servicio.'],
    ['¿Puedo hacer una aportación mensual?', 'El enlace actual de Stripe permite elegir un importe único. No se ofrece la opción mensual porque aún no se ha configurado una aportación recurrente.'],
    ['¿Cómo protege Browslium la privacidad?', 'Para decidir sobre contenido compatible, el sistema necesita analizarlo. La Política de privacidad actual explica esta web y las aportaciones voluntarias. Antes del lanzamiento general se publicarán los detalles del tratamiento y conservación de datos del servicio.'],
  ],
  ru: [
    ['Что такое Browslium?', 'Browslium — разрабатываемая система фильтрации контента. Она рассчитана на анализ поддерживаемых изображений, видео, аудио, текста и документов, поступающих пользователю, а не только на решения по сайтам целиком.'],
    ['Чем Browslium отличается от обычного интернет-фильтра?', 'Фильтрация по доменам, адресам, категориям и спискам блокировки полезна. Browslium стремится дополнить её проверкой поддерживаемых элементов внутри страницы или приложения по выбранным правилам.'],
    ['Browslium только блокирует сайты?', 'Нет. Правила для сайтов и URL могут быть частью защиты, но система также рассчитана на отдельные элементы, чтобы не применять одно решение ко всему сайту без необходимости.'],
    ['Какие виды контента предусмотрены?', 'Архитектура охватывает поддерживаемые изображения, видео, аудио, текст, документы, загрузки и веб-контент. Конкретная доступность зависит от платформы, функции и этапа разработки.'],
    ['Что такое уровни фильтрации?', 'Уровень задаёт правила обработки поддерживаемого контента. Это позволяет человеку или организации выбрать подходящую политику.'],
    ['Сколько уровней фильтрации изображений?', 'В проекте определено семь уровней. Интерактивный раздел выше объясняет каждый из них; текущая доступность зависит от платформы и функции.'],
    ['Сколько уровней фильтрации видео?', 'В проекте определено шесть уровней для видео. Для движущегося изображения нужны отдельные правила и анализ во времени.'],
    ['Зачем нужны разные уровни?', 'У людей и организаций разные требования. Несколько уровней позволяют выбрать более точные правила, чем простой переключатель «включено/выключено».'],
    ['Как работает фильтрация изображений?', 'Поддерживаемое изображение в цепочке фильтрации должно анализироваться по выбранному правилу, после чего определяется способ обработки. Пример выше объясняет правила без неподходящих изображений.'],
    ['Как работает фильтрация видео?', 'Система разрабатывается для анализа поддерживаемого видео во времени с применением отдельных правил. Работа с движущимися кадрами отличается от проверки фотографии; доступность зависит от реализации.'],
    ['Что происходит при неуверенном результате анализа?', 'Неопределённость должна обрабатываться по выбранной политике безопасности. В зависимости от контента и реализации возможны дополнительный анализ или более осторожное решение; единого производственного поведения пока не обещают.'],
    ['Предусмотрена ли фильтрация аудио и текста?', 'Да, архитектура включает для поддерживаемых аудио и текста отдельные методы анализа и правила. Эти возможности ещё разрабатываются, а их доступность зависит от платформы.'],
    ['Один элемент заблокирует всю страницу?', 'Не обязательно. Там, где это технически возможно, система должна различать элемент и страницу, чтобы решение по одному материалу не определяло судьбу остальных.'],
    ['Работает ли Browslium во всех приложениях и браузерах?', 'Универсальная поддержка не заявляется. Она зависит от ограничений ОС, устройства приложений и компонентов Browslium на конкретной платформе.'],
    ['Для каких платформ идёт разработка?', 'Работа ведётся для Android, платформ Apple и Windows. Текущий этап каждой указан в разделе статуса платформ; общего производственного выпуска здесь не объявлено.'],
    ['Замедлит ли фильтрация интернет?', 'Анализ требует времени. В архитектуре предусмотрены оптимизированные цепочки и кэширование, но задержка зависит от контента, устройства, сети и необходимого анализа; фиксированное время не обещается.'],
    ['Доступен ли Browslium сейчас?', 'Проект находится в активной разработке и тестировании. Доступность зависит от платформы и функции; актуальную сводку смотрите в разделе статуса платформ.'],
    ['Browslium предназначен только для родителей?', 'Нет. Проект рассчитан на людей, семьи, школы, компании, НКО и сообщества, которым нужен больший контроль над контентом на устройствах.'],
    ['Сколько будет стоить Browslium?', 'Цель проекта — предоставить доступ к фильтрации без платы с пользователей при поддержке добровольных взносов. Окончательные цены и доступность пока не объявлены.'],
    ['Зачем проекту добровольные взносы?', 'Разработка, тестирование, ИИ-инфраструктура, вычисления на GPU, серверы, безопасность и эксплуатация требуют затрат. Добровольная поддержка помогает оплачивать эту работу.'],
    ['Как проходят взносы?', 'Оплата происходит на странице Stripe. Сайт Browslium не получает и не хранит данные банковской карты. Взнос не является покупкой товара или услуги.'],
    ['Можно ли делать ежемесячные взносы?', 'Текущая ссылка Stripe принимает выбранную вами разовую сумму. Ежемесячная опция не показывается, поскольку регулярные взносы ещё не настроены.'],
    ['Как Browslium обращается с личными данными?', 'Для решения о поддерживаемом контенте требуется его анализ. Действующая Политика конфиденциальности описывает этот сайт и добровольные взносы. Подробности обработки и хранения данных сервиса будут опубликованы до общего выпуска.'],
  ],
  he: [
    ['מה זה Browslium?', 'Browslium היא מערכת סינון תכנים בפיתוח. היא מיועדת לנתח חומר נתמך שמגיע למשתמש — תמונות, וידאו, שמע, טקסט ומסמכים — ולא להסתמך רק על החלטה לגבי אתר שלם.'],
    ['במה Browslium שונה מסינון אינטרנט רגיל?', 'סינון לפי דומיין, כתובת, קטגוריה ורשימות חסימה עדיין שימושי. Browslium שואפת להוסיף בדיקה של פריטים נתמכים בתוך עמוד או יישום לפי המדיניות שנבחרה.'],
    ['האם Browslium רק חוסמת אתרים?', 'לא. כללים לאתרים ולכתובות יכולים להיות חלק מההגנה, אך התכנון כולל גם בדיקה של פריטים בודדים כדי שלא כל החלטה תחול על האתר כולו.'],
    ['אילו סוגי תוכן אפשר לסנן?', 'הארכיטקטורה כוללת תמונות, וידאו, שמע, טקסט, מסמכים, הורדות ותוכן רשת נתמכים. הזמינות המדויקת תלויה בפלטפורמה, בתכונה ובשלב הפיתוח.'],
    ['מהן רמות סינון?', 'כל רמה מגדירה כללים לטיפול בתוכן נתמך. כך אדם או ארגון יכולים לבחור מדיניות שמתאימה לצרכים שלהם.'],
    ['כמה רמות סינון יש לתמונות?', 'בפרויקט מוגדרות שבע רמות לתמונות. החלק האינטראקטיבי למעלה מסביר כל אחת מהן; הזמינות כיום תלויה בפלטפורמה ובתכונה.'],
    ['כמה רמות סינון יש לווידאו?', 'בפרויקט מוגדרות שש רמות לווידאו. תוכן נע דורש כללים נפרדים וניתוח לאורך זמן.'],
    ['למה יש כמה רמות במקום מתג אחד?', 'לאנשים ולארגונים יש צרכים שונים. כמה רמות מאפשרות מדיניות מדויקת יותר מאשר רק הפעלה או כיבוי.'],
    ['איך פועל סינון תמונות?', 'כאשר תמונה נתמכת עוברת במסלול הסינון, המערכת אמורה לנתח אותה לפי המדיניות שנבחרה ולהחליט כיצד לטפל בה. ההמחשה למעלה מציגה את הכללים בלי להציג תמונות לא מתאימות.'],
    ['איך פועל סינון וידאו?', 'Browslium נבנית לניתוח וידאו נתמך לאורך זמן ולהפעלת מדיניות ייעודית. ניתוח רצף תמונות שונה מניתוח תמונה בודדת; היכולות בפועל תלויות במימוש.'],
    ['מה קורה כשהמערכת אינה בטוחה?', 'אי־ודאות אמורה להיות מטופלת לפי מדיניות הבטיחות שנבחרה. בהתאם לסוג התוכן ולמימוש, ייתכנו בדיקה נוספת או טיפול מחמיר יותר; לא מובטחת התנהגות אחידה בייצור.'],
    ['האם יש גם סינון שמע וטקסט?', 'הארכיטקטורה כוללת ניתוח וכללים נפרדים לשמע ולטקסט נתמכים. היכולות האלה עדיין בפיתוח, והזמינות תלויה בפלטפורמה.'],
    ['האם פריט אחד יחסום עמוד שלם?', 'לא בהכרח. כשהדבר נתמך טכנית, המערכת אמורה להפריד בין פריט לבין העמוד שמכיל אותו, כך שהחלטה אחת לא תקבע אוטומטית לגבי כל היתר.'],
    ['האם Browslium פועלת בכל יישום ודפדפן?', 'אין טענה לכיסוי מלא. התמיכה תלויה במגבלות מערכת ההפעלה, במבנה היישום וברכיבי Browslium שקיימים בכל פלטפורמה.'],
    ['לאילו פלטפורמות Browslium מפותחת?', 'הפיתוח כולל Android, פלטפורמות Apple ו־Windows. השלב העדכני של כל אחת מופיע בחלק מצב הפלטפורמות; אין כאן הודעה על השקה כללית.'],
    ['האם הסינון יאט את האינטרנט?', 'ניתוח תוכן דורש עיבוד. התכנון כולל תהליכים יעילים וזיכרון מטמון לצמצום עיכובים, אך הזמן בפועל תלוי בתוכן, במכשיר, ברשת ובבדיקה הדרושה; אין הבטחת זמן קבוע.'],
    ['האם Browslium זמינה כבר עכשיו?', 'Browslium נמצאת בפיתוח ובבדיקות. הזמינות שונה בין פלטפורמות ותכונות; הסיכום המעודכן מופיע בחלק מצב הפלטפורמות.'],
    ['האם Browslium מיועדת רק להורים?', 'לא. היא מפותחת גם ליחידים, למשפחות, לבתי ספר, לעסקים, לעמותות ולקהילות שרוצים יותר שליטה בתוכן שמגיע למכשירים שלהם.'],
    ['כמה Browslium תעלה?', 'מטרת הפרויקט היא לאפשר גישה לסינון ללא תשלום מהמשתמשים, בעזרת תרומות מרצון. המחיר והזמינות הסופיים עדיין לא הוכרזו.'],
    ['למה מבקשים תרומות?', 'פיתוח, בדיקות, תשתיות AI, חישוב GPU, שרתים, אבטחה ותפעול עולים כסף. תמיכה מרצון עוזרת לממן את העבודה.'],
    ['איך התרומות מעובדות?', 'התשלום מתבצע בעמוד שמארחת Stripe. אתר Browslium אינו אוסף או שומר פרטי כרטיס. תרומה אינה קונה מוצר או שירות.'],
    ['אפשר לתרום בכל חודש?', 'הקישור הנוכחי ב־Stripe מאפשר לבחור סכום לתרומה חד־פעמית. אפשרות חודשית אינה מוצגת משום שתרומות חוזרות עדיין לא הוגדרו.'],
    ['איך Browslium מטפלת בפרטיות?', 'כדי לקבל החלטה על תוכן נתמך נדרש ניתוח שלו. מדיניות הפרטיות הנוכחית מסבירה את האתר ואת התרומות מרצון. פרטי העיבוד והשמירה של השירות יפורסמו לפני השקה כללית.'],
  ],
  yi: [
    ['וואָס איז Browslium?', 'Browslium איז אַן אינהאַלט־פילטער אין אַנטוויקלונג. ער זאָל אַנאַליזירן געשטיצטע בילדער, ווידעאס, אוידיאָ, טעקסט און דאָקומענטן וואָס קומען צום באַניצער, און נישט נאָר באַשליסן וועגן אַ גאַנצער וועבזײַט.'],
    ['וואָס איז אַנדערש ווי בײַ אַ געוויינטלעכן אינטערנעט־פילטער?', 'פֿילטערן לויט וועב־אַדרעסן, קאַטעגאָריעס און בלאָקיר־רשימות איז נאָך אַלץ נוצלעך. Browslium וויל דערצו קאָנטראָלירן געשטיצטע זאַכן אינעם בלאט אָדער אַפּליקאַציע לויטן אויסגעקליבענעם כלל.'],
    ['בלאָקירט Browslium נאָר וועבזײַטן?', 'ניין. כללים פֿאַר וועבזײַטן און אַדרעסן קענען געהערן צום שוץ, אָבער דער פּלאַן קאָנטראָלירט אויך איינצלנע זאַכן, כּדי נישט יעדן באַשלוס צו אָנווענדן אויפֿן גאַנצן וועבזײַט.'],
    ['וועלכע סאָרטן אינהאַלט קען מען פֿילטערן?', 'די סיסטעם נעמט אַרײַן געשטיצטע בילדער, ווידעאס, אוידיאָ, טעקסט, דאָקומענטן, אַראָפּלאָדונגען און וועב־אינהאַלט. וואָס איז טאַקע פֿאַראַן ווענדט זיך אָן אין פּלאַטפאָרמע, פונקציע און אַנטוויקלונג־שטופֿע.'],
    ['וואָס זענען פילטער־שטאַפּלען?', 'יעדער שטאַפּל באַשטימט ווי צו באַהאַנדלען געשטיצטן אינהאַלט. אַזוי קען אַ מענטש אָדער אָרגאַניזאַציע אויסקלײַבן כללים וואָס פּאַסן צו די אייגענע באַדערפֿענישן.'],
    ['וויפֿל שטאַפּלען זענען דאָ פֿאַר בילדער?', 'דער פּראָיעקט האָט זיבן בילד־שטאַפּלען. דער אינטעראַקטיווער טייל אויבן דערקלערט יעדן כלל; די איצטיקע פֿאַראַנקייט ווענדט זיך אָן אין פּלאַטפאָרמע און פונקציע.'],
    ['וויפֿל שטאַפּלען זענען דאָ פֿאַר ווידעאס?', 'דער פּראָיעקט האָט זעקס ווידעאָ־שטאַפּלען. באַוועגלעכער אינהאַלט דאַרף אייגענע כללים און אַן אַנאַליז דורכן צײַט.'],
    ['פֿאַר וואָס דאַרף מען עטלעכע שטאַפּלען?', 'מענטשן און אָרגאַניזאַציעס האָבן פֿאַרשיידענע באַדערפֿענישן. עטלעכע שטאַפּלען געבן אַ פּינקטלעכערן אויסוואַל ווי אַ פּשוטער אָנ־אויס־קנעפּל.'],
    ['ווי אַרבעט דער בילד־פילטער?', 'ווען אַ געשטיצטער בילד גייט דורכן פילטער, זאָל די סיסטעם אים אַנאַליזירן לויטן אויסגעקליבענעם כלל און באַשליסן ווי צו באַהאַנדלען אים. דער בײַשפּיל אויבן ווײַזט דעם געדאַנק אָן אומפּאַסיקע בילדער.'],
    ['ווי אַרבעט דער ווידעאָ־פילטער?', 'Browslium ווערט געבויט צו אַנאַליזירן געשטיצטן ווידעאָ דורכן צײַט מיט באַזונדערע כללים. באַוועגלעכע בילדער דאַרפֿן אַן אַנדערן פּראָצעס ווי אַ שטילער בילד; די אמתע פֿאַראַנקייט ווענדט זיך אָן אין דער אויספֿירונג.'],
    ['וואָס געשעט ווען די סיסטעם איז נישט זיכער?', 'בײַ אומזיכערקייט זאָל מען גיין לויטן אויסגעקליבענעם זיכערקייט־כלל. לויטן אינהאַלט און דער אויספֿירונג קען מען נאָך אַ מאָל קאָנטראָלירן אָדער זײַן מער פֿאַרזיכטיק; מע צוזאָגט נישט איין פֿעסטע רעאַקציע אין פּראָדוקציע.'],
    ['ווערן אוידיאָ און טעקסט אויך געפֿילטערט?', 'די אַרכיטעקטור האָט באַזונדערע אַנאַליז און כללים פֿאַר געשטיצטן אוידיאָ און טעקסט. די פונקציעס זענען נאָך אין אַנטוויקלונג, און זייער פֿאַראַנקייט ווענדט זיך אָן אין פּלאַטפאָרמע.'],
    ['קען איין זאַך בלאָקירן אַ גאַנצן בלאט?', 'נישט אומבאַדינגט. וווּ עס איז טעקניש מעגלעך, זאָל די סיסטעם אונטערשיידן צווישן אַן איינצלנער זאַך און דעם בלאט, כּדי איין באַשלוס זאָל נישט באַשטימען פֿאַר אַלע אַנדערע.'],
    ['אַרבעט Browslium אין יעדער אַפּליקאַציע און בלעטערער?', 'מע זאָגט נישט אַז די דעקונג איז איבעראַל. זי ווענדט זיך אָן אין די גרענעצן פֿונעם אָפּעראַציע־סיסטעם, דעם בוי פֿון דער אַפּליקאַציע און די פֿאַראַנענע Browslium־טיילן.'],
    ['פֿאַר וועלכע פּלאַטפאָרמעס בויט מען עס?', 'מע אַרבעט אויף Android, Apple־פּלאַטפאָרמעס און Windows. דער איצטיקער שטאַנד פֿון יעדער איינציקער שטייט אינעם פּלאַטפאָרמע־טייל; קיין אַלגעמיינער אַרויסלאָז ווערט דאָ נישט געמאָלדן.'],
    ['וועט פֿילטערן פֿאַרלאַנגזאַמען דעם אינטערנעט?', 'אַנאַליז דאַרף צײַט. דער פּלאַן ניצט אָפּטימיזירטע פּראָצעסן און קאַש, אָבער דער אמתער פֿאַרzug ווענדט זיך אָן אין אינהאַלט, מיטל, נעץ און אַנאַליז; קיין פֿעסטע שנעלקייט ווערט נישט צוגעזאָגט.'],
    ['איז Browslium שוין פֿאַראַן?', 'Browslium איז אין אַקטיווער אַנטוויקלונג און פּרוּוון. די פֿאַראַנקייט ווענדט זיך אָן אין פּלאַטפאָרמע און פונקציע; דער איצטיקער איבערבליק שטייט אינעם פּלאַטפאָרמע־טייל.'],
    ['איז Browslium נאָר פֿאַר עלטערן?', 'ניין. עס ווערט געבויט פֿאַר יחידים, משפּחות, שולן, געשעפֿטן, נישט־פּראָפֿיט־אָרגאַניזאַציעס און קהילות וואָס ווילן מער קאָנטראָל איבערן אינהאַלט אויף זייערע מיטלען.'],
    ['וויפֿל וועט Browslium קאָסטן?', 'דער ציל איז צו מאַכן דעם פילטער צוטריטלעך אָן אָפּצאָל פֿון באַניצערס, מיט הילף פֿון פֿרײַוויליקע בײַשטײַערן. ענדגילטיקע פּרײַזן און פֿאַראַנקייט זענען נאָך נישט באַקאַנט געמאַכט געוואָרן.'],
    ['פֿאַר וואָס בעט דער פּראָיעקט בײַשטײַערן?', 'אַנטוויקלונג, פּרוּוון, AI־אינפֿראַסטרוקטור, GPU־רעכענונג, סערווערס, זיכערקייט און אויפֿהאַלט האָבן קאָסטן. פֿרײַוויליקע הילף שטיצט די אַרבעט.'],
    ['ווי ווערן בײַשטײַערן באַאַרבעט?', 'די צאָלונג גייט דורך אַ זײַט פֿון Stripe. די Browslium־וועבזײַט נעמט נישט און היט נישט קיין קאָרט־דאַטן. אַ בײַשטײַער קויפֿט נישט קיין פּראָדוקט אָדער דינסט.'],
    ['קען מען יעדן חודש בײַשטײַערן?', 'דער איצטיקער Stripe־לינק נעמט אַ איין־מאָליקן סכום וואָס איר קלײַבט אויס. אַ חודשלעכער אויסוואַל ווערט נישט געוויזן, ווײַל רעגולערע בײַשטײַערן זענען נאָך נישט אײַנגעשטעלט.'],
    ['ווי היט Browslium די פּריוואַטקייט?', 'כּדי צו באַשליסן וועגן געשטיצטן אינהאַלט מוז מען אים אַנאַליזירן. די איצטיקע פּריוואַטקייט־פּאָליטיק דערקלערט דעם וועבזײַט און פֿרײַוויליקע בײַשטײַערן. פּרטים וועגן באַאַרבעטונג און אויפֿהיטן פֿון דינסט־דאַטן וועלן דערשײַנען פֿאַרן אַלגעמיינעם אַרויסלאָז.'],
  ],
  'pt-BR': [
    ['O que é o Browslium?', 'O Browslium é um sistema de filtragem de conteúdo em desenvolvimento. Ele foi pensado para analisar material compatível que chega ao usuário — imagens, vídeos, áudio, texto e documentos — além das decisões sobre sites inteiros.'],
    ['Qual é a diferença para um filtro de internet tradicional?', 'Regras por domínio, URL, categoria e lista de bloqueio continuam úteis. O Browslium busca acrescentar análise de itens compatíveis dentro da página ou aplicativo conforme a política escolhida.'],
    ['O Browslium só bloqueia sites?', 'Não. Regras para sites e URLs podem fazer parte da proteção, mas o projeto também avalia itens individuais compatíveis sem necessariamente aplicar a mesma decisão ao site inteiro.'],
    ['Que tipos de conteúdo podem ser filtrados?', 'A arquitetura contempla imagens, vídeos, áudio, texto, documentos, downloads e conteúdo web compatíveis. A disponibilidade exata depende da plataforma, do recurso e do estágio de desenvolvimento.'],
    ['O que são níveis de filtragem?', 'Cada nível reúne regras para tratar conteúdo compatível. Isso permite que pessoas e organizações escolham uma política adequada às suas necessidades.'],
    ['Quantos níveis existem para imagens?', 'O projeto define sete níveis para imagens. A seção interativa acima explica cada política; a disponibilidade atual varia por plataforma e recurso.'],
    ['Quantos níveis existem para vídeos?', 'O projeto define seis níveis para vídeos. Conteúdo em movimento exige regras próprias e análise ao longo do tempo.'],
    ['Por que usar vários níveis?', 'Pessoas e organizações têm critérios diferentes. Vários níveis permitem uma política mais precisa que um simples botão de ligar ou desligar.'],
    ['Como funciona o filtro de imagens?', 'Quando uma imagem compatível passa pelo fluxo de filtragem, o sistema deve analisá-la segundo a política selecionada e decidir como tratá-la. O exemplo acima ilustra as regras sem imagens inadequadas.'],
    ['Como funciona o filtro de vídeos?', 'O Browslium está sendo desenvolvido para analisar vídeos compatíveis ao longo do tempo e aplicar uma política específica. Processar quadros em movimento difere de analisar uma imagem fixa; a disponibilidade depende da implementação.'],
    ['E se o sistema não tiver certeza?', 'A incerteza deve seguir a política de segurança escolhida. Dependendo do conteúdo e da implementação, pode haver análise adicional ou tratamento mais conservador; não se promete um comportamento único em produção.'],
    ['Também há filtro de áudio e texto?', 'A arquitetura inclui análise e regras separadas para áudio e texto compatíveis. Esses recursos ainda estão em desenvolvimento, e a disponibilidade varia por plataforma.'],
    ['Um item pode bloquear a página inteira?', 'Não necessariamente. Quando houver suporte técnico, o sistema deve distinguir o item da página para que uma decisão não determine automaticamente o resultado dos demais conteúdos.'],
    ['Funciona em todos os apps e navegadores?', 'Não há promessa de cobertura universal. Ela depende das restrições do sistema operacional, da arquitetura dos apps e dos componentes do Browslium disponíveis em cada plataforma.'],
    ['Para quais plataformas o Browslium está sendo desenvolvido?', 'O trabalho inclui Android, plataformas Apple e Windows. Veja a etapa atual de cada uma na seção de plataformas; não há anúncio de lançamento geral.'],
    ['O filtro vai deixar a internet mais lenta?', 'A análise exige processamento. O projeto usa fluxos otimizados e cache para reduzir atrasos, mas o tempo real varia conforme o conteúdo, dispositivo, rede e análise; não há promessa de latência fixa.'],
    ['O Browslium já está disponível?', 'O projeto está em desenvolvimento e testes. A disponibilidade varia por plataforma e recurso; a seção de plataformas traz o resumo atualizado.'],
    ['O Browslium é só para pais?', 'Não. Ele foi pensado para pessoas, famílias, escolas, empresas, organizações sem fins lucrativos e comunidades que querem mais controle sobre o conteúdo nos dispositivos.'],
    ['Quanto vai custar?', 'A meta do projeto é oferecer acesso ao filtro sem cobrar dos usuários, com apoio de contribuições voluntárias. Preço e disponibilidade definitivos ainda não foram anunciados.'],
    ['Por que o projeto pede contribuições?', 'Engenharia, testes, infraestrutura de IA, computação em GPU, servidores, segurança e operação têm custos. O apoio voluntário ajuda a financiar esse trabalho.'],
    ['Como as contribuições são processadas?', 'O pagamento acontece em uma página hospedada pelo Stripe. O site do Browslium não coleta nem armazena dados do cartão. Contribuir não compra um produto ou serviço.'],
    ['Posso contribuir todo mês?', 'O link atual do Stripe aceita um valor único escolhido por você. A opção mensal não aparece porque contribuições recorrentes ainda não foram configuradas.'],
    ['Como o Browslium lida com a privacidade?', 'É necessário analisar conteúdo compatível para tomar decisões de filtragem. A Política de Privacidade atual explica este site e as contribuições voluntárias. O tratamento e a retenção de dados do serviço serão detalhados antes do lançamento geral.'],
  ],
  fr: [
    ['Qu’est-ce que Browslium ?', 'Browslium est un système de filtrage de contenu en développement. Il vise à analyser les contenus compatibles reçus par l’utilisateur — images, vidéos, sons, textes et documents — au-delà des seules décisions concernant un site entier.'],
    ['Quelle différence avec un filtre Internet classique ?', 'Les règles par domaine, URL, catégorie et liste de blocage restent utiles. Browslium entend y ajouter l’analyse d’éléments compatibles dans une page ou une application selon la règle choisie.'],
    ['Browslium bloque-t-il seulement des sites ?', 'Non. Les règles de sites et d’URL peuvent faire partie de la protection, mais le projet prévoit aussi l’analyse d’éléments distincts, sans imposer systématiquement la même décision à tout le site.'],
    ['Quels contenus peuvent être filtrés ?', 'L’architecture prévoit les images, vidéos, sons, textes, documents, téléchargements et contenus web compatibles. La disponibilité exacte dépend de la plateforme, de la fonction et de l’avancement du projet.'],
    ['Que sont les niveaux de filtrage ?', 'Chaque niveau définit des règles pour traiter un contenu compatible. Une personne ou une organisation peut ainsi choisir une politique adaptée à ses besoins.'],
    ['Combien de niveaux pour les images ?', 'Le projet définit sept niveaux pour les images. La section interactive ci-dessus explique chaque règle ; leur disponibilité actuelle varie selon la plateforme et la fonction.'],
    ['Combien de niveaux pour les vidéos ?', 'Le projet définit six niveaux pour les vidéos. Le contenu en mouvement demande des règles propres et une analyse dans le temps.'],
    ['Pourquoi plusieurs niveaux plutôt qu’un interrupteur ?', 'Les attentes varient d’une personne ou organisation à l’autre. Plusieurs niveaux permettent un choix plus précis qu’un simple marche/arrêt.'],
    ['Comment fonctionne le filtrage des images ?', 'Lorsqu’une image compatible entre dans le parcours de filtrage, le système doit l’analyser selon la règle choisie puis décider de son traitement. L’exemple ci-dessus illustre les règles sans images inadaptées.'],
    ['Comment fonctionne le filtrage des vidéos ?', 'Browslium est conçu pour analyser les vidéos compatibles dans le temps et appliquer une règle spécifique. Des images en mouvement ne se traitent pas comme une photo ; la disponibilité dépend de l’implémentation.'],
    ['Que se passe-t-il en cas d’incertitude ?', 'L’incertitude doit être gérée selon la politique de sécurité choisie. Selon le contenu et l’implémentation, une analyse supplémentaire ou un traitement plus prudent peut être nécessaire ; aucun comportement unique en production n’est promis.'],
    ['Le son et le texte sont-ils aussi filtrés ?', 'L’architecture prévoit une analyse et des règles distinctes pour les sons et textes compatibles. Ces fonctions sont en développement et leur disponibilité dépend de la plateforme.'],
    ['Un seul élément peut-il bloquer toute une page ?', 'Pas nécessairement. Lorsque la technique le permet, le système doit distinguer un élément de sa page pour qu’une décision ne détermine pas automatiquement le sort de tous les autres contenus.'],
    ['Browslium fonctionne-t-il dans toutes les applications ?', 'Aucune couverture universelle n’est annoncée. Elle dépend des limites du système d’exploitation, de l’architecture des applications et des composants Browslium disponibles.'],
    ['Sur quelles plateformes travaillez-vous ?', 'Le développement concerne Android, les plateformes Apple et Windows. Consultez la section Plateformes pour l’état actuel de chacune ; aucun lancement général n’est annoncé ici.'],
    ['Le filtrage ralentira-t-il ma connexion ?', 'L’analyse demande du traitement. Le projet prévoit des parcours optimisés et du cache, mais le délai réel dépend du contenu, de l’appareil, du réseau et de l’analyse ; aucune latence fixe n’est promise.'],
    ['Browslium est-il déjà disponible ?', 'Browslium est en développement et en test. La disponibilité varie selon la plateforme et la fonction ; la section Plateformes présente le résumé à jour.'],
    ['Browslium est-il réservé aux parents ?', 'Non. Il est pensé pour les particuliers, familles, écoles, entreprises, associations et communautés qui souhaitent mieux maîtriser le contenu reçu sur leurs appareils.'],
    ['Combien coûtera Browslium ?', 'Le projet vise un accès au filtrage sans frais pour les utilisateurs, soutenu par des contributions volontaires. Les tarifs et la disponibilité définitifs n’ont pas encore été annoncés.'],
    ['Pourquoi demander des contributions ?', 'Ingénierie, tests, infrastructure IA, calcul GPU, serveurs, sécurité et fonctionnement ont un coût. Les contributions volontaires aident à financer ces travaux.'],
    ['Comment les contributions sont-elles traitées ?', 'Le paiement se fait sur une page hébergée par Stripe. Le site Browslium ne collecte ni ne conserve les données de carte. Contribuer n’achète ni produit ni service.'],
    ['Puis-je contribuer chaque mois ?', 'Le lien Stripe actuel permet de choisir un montant ponctuel. L’option mensuelle n’est pas affichée, car les contributions récurrentes ne sont pas configurées.'],
    ['Comment Browslium protège-t-il la vie privée ?', 'Décider du traitement d’un contenu compatible nécessite son analyse. La Politique de confidentialité actuelle explique ce site et les contributions volontaires. Le traitement et la conservation des données du service seront détaillés avant son lancement général.'],
  ],
};
