// New public-website policies. They cover this informational website and its
// voluntary Stripe link, not an unreleased filtering service. Do not insert
// product data-retention or deployment claims without a verified production
// architecture and legal review.
export const legal = {
  en: {
    privacy: {
      title:'Privacy Policy',
      description:'Learn how the Browslium website uses language preferences, handles contact messages and links to Stripe for voluntary contributions.',
      intro:'This policy covers the public Browslium website. Browslium’s filtering service is in development and testing; this site does not itself inspect your browsing content.',
      updated:'Published October 6, 2026',
      sections:[
        ['Who we are','Browslium LLC operates this website. For a privacy question or request, write to admin@browslium.com.'],
        ['Browsing this site','The site is a static website. We have not installed advertising trackers or a third-party analytics script. The hosting provider may process technical data, such as your IP address, browser, requested page and time, to deliver and protect the site. We do not use this website to inspect the content of other sites you visit.'],
        ['Language preference','The site reads your browser language settings to offer a one-time language suggestion. If you select a language, your choice is saved in your browser’s local storage so it takes priority on later visits. Dismissing the suggestion is also saved locally. These settings are not sent to Browslium by the language feature, and you can remove them using your browser’s site-data controls.'],
        ['Contact by email','A contact link opens your own email application. If you email us, we receive the address and information you choose to send. Avoid passwords, payment-card numbers and other sensitive material. We use your message to answer or investigate your request and may keep correspondence while needed for that purpose or legal obligations. Ask us about access or deletion at the same address.'],
        ['Voluntary contributions','The donation button opens a payment page hosted by Stripe. Stripe handles payment-card information under its own privacy terms. This website does not collect or store your card details. Browslium may receive contribution records and contact details that Stripe makes available to the account holder to administer contributions, accounting or required records. A contribution does not buy product access.'],
        ['Future filtering service','The planned product needs to analyze supported content to make filtering decisions. This website does not activate that processing. Before general access to the service, we will publish separate, accurate information about product data flows, retention, security and user choices based on the production system. We do not claim that the future service processes nothing or stores nothing.'],
        ['Requests, security and changes','You may contact us about information you provided by email or through a contribution. We may need to verify a request and keep records required by law. Data may be processed by our hosting, email or payment providers in other countries. No website can promise absolute security. If this policy changes materially, we will update its date and content.'],
      ],
    },
    terms: {
      title:'Website Terms',
      description:'Terms for using the informational Browslium website and making voluntary contributions through Stripe.',
      intro:'These terms apply to this public website. Browslium is under development; this site does not enroll a device, provide a production filtering account or create a service subscription.',
      updated:'Published October 6, 2026',
      sections:[
        ['About this website','Browslium LLC publishes information about a content-filtering system being developed and tested. Descriptions of policies and planned features explain the design and do not promise that a feature is available for every device, app or browser. Platform status on the site should be read as a development update, not an offer of immediate access.'],
        ['Use of content','The Browslium name, logo, illustrations, text and website design belong to Browslium LLC or their respective rights holders. You may read and share a link to this site. Do not misrepresent the project, impersonate Browslium or use the site to interfere with its operation.'],
        ['Voluntary contributions','The support button takes you to a Stripe-hosted page where you choose a one-time amount. A contribution is voluntary and does not purchase a product, subscription, preferential access or a guaranteed outcome. The current link does not offer a monthly plan. Payment and any refunds are handled under the applicable Stripe checkout and payment rules.'],
        ['No tax representation','Browslium does not state that a contribution is tax-deductible. Tax treatment depends on the donor’s circumstances and jurisdiction; seek independent advice if needed.'],
        ['External services','Stripe and other external destinations linked from this site have their own terms and privacy practices. We are not responsible for the operation or content of sites we do not control.'],
        ['Accuracy and limits','We try to keep product information current, but development can change. Automated content filtering can make errors, and no coverage, performance or release date is guaranteed by this website. Nothing here replaces a future product agreement, privacy notice or legally required terms before service activation. Mandatory rights under applicable law remain in effect.'],
        ['Contact and changes','Questions about this website or a contribution can be sent to admin@browslium.com. We may update these website terms as the project changes and will show a new publication date for material revisions.'],
      ],
    },
  },
  es: {
    privacy: {
      title:'Política de privacidad',
      description:'Cómo la web de Browslium usa las preferencias de idioma, recibe correos y enlaza a Stripe para aportaciones voluntarias.',
      intro:'Esta política se aplica al sitio público de Browslium. El servicio de filtrado está en desarrollo y pruebas; esta web no inspecciona el contenido de tu navegación.',
      updated:'Publicada el 6 de octubre de 2026',
      sections:[
        ['Quiénes somos','Browslium LLC opera esta web. Para consultas o solicitudes de privacidad, escribe a admin@browslium.com.'],
        ['Visitar esta web','Es un sitio estático. No hemos instalado rastreadores publicitarios ni scripts de analítica de terceros. El proveedor de alojamiento puede procesar datos técnicos como dirección IP, navegador, página solicitada y hora para servir y proteger el sitio. Esta web no inspecciona el contenido de otros sitios que visitas.'],
        ['Preferencia de idioma','La web consulta los idiomas configurados en tu navegador para ofrecer una sugerencia una sola vez. Si eliges un idioma, guardamos esa decisión en el almacenamiento local del navegador para respetarla en visitas posteriores. También se guarda localmente si descartas el aviso. La función de idioma no envía estos ajustes a Browslium. Puedes borrarlos desde la configuración de datos del sitio en tu navegador.'],
        ['Contacto por correo','El enlace de contacto abre tu aplicación de correo. Si nos escribes, recibimos tu dirección y la información que decidas enviar. Evita contraseñas, números de tarjeta y otros datos sensibles. Usamos el mensaje para responder o investigar tu solicitud y podemos conservar la correspondencia mientras sea necesaria para ese fin o por obligaciones legales. Puedes consultar sobre acceso o eliminación en el mismo correo.'],
        ['Aportaciones voluntarias','El botón de aportación abre una página de pago alojada por Stripe. Stripe trata los datos de tarjeta bajo sus propias condiciones de privacidad. Esta web no recoge ni almacena esos datos. Browslium puede recibir registros de aportaciones y datos de contacto que Stripe facilite al titular de la cuenta para gestionar las aportaciones, la contabilidad o los registros exigidos. Aportar no compra acceso al producto.'],
        ['Futuro servicio de filtrado','El producto previsto necesita analizar contenido compatible para tomar decisiones de filtrado. Esta web no activa ese tratamiento. Antes de ofrecer acceso general al servicio, publicaremos información separada y precisa sobre flujos de datos, conservación, seguridad y opciones de usuario basada en el sistema de producción. No afirmamos que el futuro servicio no procese ni almacene nada.'],
        ['Solicitudes, seguridad y cambios','Puedes escribirnos sobre la información que enviaste por correo o mediante una aportación. Tal vez debamos verificar la solicitud y conservar registros exigidos por ley. Nuestros proveedores de alojamiento, correo o pagos pueden tratar datos en otros países. Ninguna web garantiza seguridad absoluta. Si esta política cambia de forma importante, actualizaremos su fecha y contenido.'],
      ],
    },
    terms: {
      title:'Términos del sitio web',
      description:'Condiciones para usar la web informativa de Browslium y hacer aportaciones voluntarias mediante Stripe.',
      intro:'Estos términos se aplican a esta web pública. Browslium está en desarrollo: el sitio no inscribe dispositivos, no proporciona una cuenta de filtrado en producción y no crea una suscripción al servicio.',
      updated:'Publicados el 6 de octubre de 2026',
      sections:[
        ['Sobre esta web','Browslium LLC publica información sobre un sistema de filtrado de contenido en desarrollo y pruebas. Las descripciones de políticas y funciones previstas explican el diseño; no prometen que una función esté disponible en todos los dispositivos, aplicaciones o navegadores. El estado por plataforma es una actualización de desarrollo, no una oferta de acceso inmediato.'],
        ['Uso del contenido','El nombre, logotipo, ilustraciones, textos y diseño de Browslium pertenecen a Browslium LLC o a sus titulares correspondientes. Puedes leer el sitio y compartir su enlace. No tergiverses el proyecto, suplantes a Browslium ni uses la web para interferir con su funcionamiento.'],
        ['Aportaciones voluntarias','El botón de apoyo abre una página de Stripe donde eliges un importe único. La aportación es voluntaria y no compra un producto, suscripción, acceso preferente ni un resultado garantizado. El enlace actual no ofrece un plan mensual. El pago y posibles reembolsos se rigen por las reglas aplicables de la página de pago y Stripe.'],
        ['Sin promesa de deducción fiscal','Browslium no afirma que una aportación sea deducible de impuestos. El tratamiento fiscal depende de la situación y jurisdicción de quien aporta; busca asesoría independiente si la necesitas.'],
        ['Servicios externos','Stripe y otros destinos externos enlazados desde esta web tienen sus propias condiciones y prácticas de privacidad. No controlamos ni respondemos por el funcionamiento o contenido de sitios ajenos.'],
        ['Exactitud y límites','Procuramos mantener actualizada la información, pero el desarrollo puede cambiar. El filtrado automático puede equivocarse y esta web no garantiza cobertura, rendimiento ni fecha de lanzamiento. Nada aquí sustituye un futuro contrato de producto, aviso de privacidad o condiciones legalmente exigidas antes de activar el servicio. Los derechos irrenunciables de la ley aplicable permanecen vigentes.'],
        ['Contacto y cambios','Para consultas sobre la web o una aportación, escribe a admin@browslium.com. Podemos actualizar estos términos a medida que avance el proyecto y mostraremos una nueva fecha de publicación cuando haya cambios importantes.'],
      ],
    },
  },
  ru: {
    privacy: {
      title:'Политика конфиденциальности',
      description:'Как сайт Browslium использует языковые настройки, обрабатывает письма и направляет к Stripe для добровольных взносов.',
      intro:'Эта политика относится к публичному сайту Browslium. Служба фильтрации находится в разработке и тестировании; сам сайт не проверяет содержимое вашего просмотра других сайтов.',
      updated:'Опубликовано 6 октября 2026 года',
      sections:[
        ['Кто мы','Этот сайт ведёт Browslium LLC. По вопросам конфиденциальности пишите на admin@browslium.com.'],
        ['Посещение сайта','Это статический сайт. Мы не установили рекламные средства отслеживания или сторонний скрипт аналитики. Хостинг может обрабатывать технические данные, например IP-адрес, браузер, запрошенную страницу и время, чтобы доставлять и защищать сайт. Этот сайт не анализирует содержание других посещаемых вами сайтов.'],
        ['Языковые настройки','Сайт читает языки вашего браузера, чтобы один раз предложить подходящую версию. Выбранный язык сохраняется в локальном хранилище браузера и имеет приоритет при последующих посещениях. Отказ от подсказки тоже сохраняется локально. Языковая функция не отправляет эти настройки Browslium. Удалить их можно через настройки данных сайтов в браузере.'],
        ['Письма нам','Контактная ссылка открывает ваше почтовое приложение. Если вы пишете нам, мы получаем ваш адрес и информацию, которую вы решите отправить. Не отправляйте пароли, номера банковских карт и другие чувствительные данные. Мы используем письмо для ответа или рассмотрения запроса и можем хранить переписку, пока это необходимо для данной цели или по закону. По тому же адресу можно запросить доступ или удаление.'],
        ['Добровольные взносы','Кнопка поддержки открывает страницу оплаты Stripe. Данные банковской карты обрабатывает Stripe по собственным правилам конфиденциальности. Этот сайт не собирает и не хранит данные карты. Browslium может получать сведения о взносах и контакты, которые Stripe предоставляет владельцу счёта для учёта взносов и обязательных записей. Взнос не покупает доступ к продукту.'],
        ['Будущая служба фильтрации','Планируемому продукту нужен анализ поддерживаемого содержимого для принятия решений. Этот сайт такой анализ не запускает. До общего доступа к службе мы отдельно опубликуем точные сведения о потоках данных, хранении, безопасности и выборе пользователей на основании производственной системы. Мы не утверждаем, что будущая служба ничего не обрабатывает или не хранит.'],
        ['Запросы, безопасность и изменения','Вы можете написать нам о данных, переданных по почте или через взнос. Нам может потребоваться подтвердить запрос и сохранить записи, обязательные по закону. Хостинг, почта или платёжные поставщики могут обрабатывать данные в других странах. Ни один сайт не гарантирует абсолютную безопасность. При существенном изменении политики обновятся дата и текст.'],
      ],
    },
    terms: {
      title:'Условия сайта',
      description:'Правила использования информационного сайта Browslium и добровольных взносов через Stripe.',
      intro:'Эти условия действуют для публичного сайта. Browslium находится в разработке: сайт не регистрирует устройства, не предоставляет рабочую учётную запись фильтрации и не создаёт подписку на услугу.',
      updated:'Опубликовано 6 октября 2026 года',
      sections:[
        ['О сайте','Browslium LLC публикует сведения о разрабатываемой и тестируемой системе фильтрации контента. Описания правил и намеченных функций объясняют замысел и не обещают работу на каждом устройстве, в каждом приложении или браузере. Статус платформ — сообщение о разработке, а не предложение немедленного доступа.'],
        ['Использование материалов','Название Browslium, логотип, иллюстрации, тексты и дизайн принадлежат Browslium LLC или соответствующим правообладателям. Вы можете читать сайт и делиться ссылкой. Нельзя искажать сведения о проекте, выдавать себя за Browslium или мешать работе сайта.'],
        ['Добровольные взносы','Кнопка поддержки ведёт на страницу Stripe, где вы выбираете разовую сумму. Взнос доброволен и не покупает продукт, подписку, преимущественный доступ или гарантированный результат. Текущая ссылка не предлагает ежемесячный план. Оплата и возможные возвраты регулируются правилами соответствующей платёжной страницы и Stripe.'],
        ['Налоговый вычет не обещается','Browslium не заявляет, что взнос даёт право на налоговый вычет. Налоговые последствия зависят от обстоятельств и юрисдикции плательщика; при необходимости получите независимую консультацию.'],
        ['Внешние сервисы','У Stripe и других внешних сайтов, на которые ведут ссылки, свои условия и правила приватности. Мы не управляем чужими сайтами и не отвечаем за их работу или содержание.'],
        ['Точность и ограничения','Мы стараемся поддерживать сведения в актуальном состоянии, но разработка может меняться. Автоматическая фильтрация может ошибаться; этот сайт не гарантирует покрытие, быстродействие или дату выпуска. Эти материалы не заменяют будущий договор о продукте, уведомление о конфиденциальности или необходимые юридические условия до активации услуги. Обязательные права по закону сохраняются.'],
        ['Связь и изменения','Вопросы о сайте или взносе направляйте на admin@browslium.com. Мы можем менять эти условия по мере развития проекта и укажем новую дату публикации при существенных изменениях.'],
      ],
    },
  },
  he: {
    privacy: {
      title:'מדיניות פרטיות',
      description:'איך אתר Browslium משתמש בהעדפת שפה, מטפל בפניות בדוא״ל ומפנה ל־Stripe לתרומות מרצון.',
      intro:'מדיניות זו חלה על האתר הציבורי של Browslium. שירות הסינון נמצא בפיתוח ובבדיקות; האתר עצמו אינו בודק את תוכן הגלישה שלך באתרים אחרים.',
      updated:'פורסם ב־6 באוקטובר 2026',
      sections:[
        ['מי אנחנו','Browslium LLC מפעילה את האתר הזה. לשאלה או בקשה בנוגע לפרטיות, כתבו ל־admin@browslium.com.'],
        ['גלישה באתר','זהו אתר סטטי. לא התקנו בו כלי מעקב לפרסום או סקריפט אנליטיקה של צד שלישי. ספק האחסון עשוי לעבד מידע טכני כגון כתובת IP, דפדפן, עמוד מבוקש ושעה כדי להציג את האתר ולהגן עליו. האתר אינו מנתח את התוכן של אתרים אחרים שבהם אתם גולשים.'],
        ['העדפת שפה','האתר קורא את הגדרות השפה בדפדפן כדי להציע פעם אחת שפה מתאימה. בחירה ידנית נשמרת באחסון המקומי של הדפדפן ומקבלת עדיפות בביקורים הבאים. גם סגירת ההצעה נשמרת מקומית. פונקציית השפה אינה שולחת את ההגדרות האלה ל־Browslium. אפשר למחוק אותן דרך הגדרות נתוני האתרים בדפדפן.'],
        ['פנייה בדוא״ל','קישור יצירת הקשר פותח את תוכנת הדוא״ל שלכם. אם תכתבו לנו, נקבל את הכתובת ואת המידע שבחרתם לשלוח. הימנעו מסיסמאות, מספרי כרטיס ומידע רגיש אחר. נשתמש בהודעה כדי להשיב או לבדוק את הבקשה, וייתכן שנשמור את ההתכתבות כל עוד היא נחוצה לכך או לפי חובה חוקית. אפשר לפנות באותה כתובת בעניין עיון או מחיקה.'],
        ['תרומות מרצון','כפתור התרומה פותח עמוד תשלום שמארחת Stripe. Stripe מטפלת בפרטי כרטיס האשראי לפי כללי הפרטיות שלה. האתר הזה אינו אוסף או שומר פרטי כרטיס. Browslium עשויה לקבל רישומי תרומות ופרטי קשר ש־Stripe מעמידה לרשות בעל החשבון לצורך ניהול התרומות, חשבונאות ורישום נדרש. תרומה אינה קונה גישה למוצר.'],
        ['שירות הסינון העתידי','המוצר המתוכנן צריך לנתח תוכן נתמך כדי לקבל החלטות סינון. האתר הזה אינו מפעיל את העיבוד הזה. לפני פתיחת השירות לקהל הרחב נפרסם בנפרד מידע מדויק על זרימת הנתונים, שמירתם, האבטחה ואפשרויות המשתמשים, על סמך המערכת שתופעל בפועל. איננו טוענים שהשירות העתידי אינו מעבד או שומר דבר.'],
        ['בקשות, אבטחה ושינויים','אפשר לפנות אלינו לגבי מידע שנשלח בדוא״ל או במסגרת תרומה. ייתכן שנצטרך לאמת בקשה ולשמור רישומים הנדרשים בחוק. ספקי אחסון, דוא״ל ותשלום עשויים לעבד מידע במדינות אחרות. שום אתר אינו יכול להבטיח אבטחה מוחלטת. אם המדיניות תשתנה מהותית, נעדכן את תאריך הפרסום ואת התוכן.'],
      ],
    },
    terms: {
      title:'תנאי האתר',
      description:'תנאים לשימוש באתר המידע של Browslium ולתרומות מרצון דרך Stripe.',
      intro:'תנאים אלה חלים על האתר הציבורי. Browslium נמצאת בפיתוח; האתר אינו רושם מכשירים, אינו מספק חשבון סינון פעיל ואינו יוצר מנוי לשירות.',
      updated:'פורסם ב־6 באוקטובר 2026',
      sections:[
        ['על האתר','Browslium LLC מפרסמת מידע על מערכת סינון תכנים הנמצאת בפיתוח ובבדיקות. תיאורי המדיניות והתכונות המתוכננות מסבירים את התכנון ואינם מבטיחים שתכונה תעבוד בכל מכשיר, יישום או דפדפן. מצב הפלטפורמות הוא עדכון פיתוח, לא הצעה לגישה מיידית.'],
        ['שימוש בתוכן','השם Browslium, הלוגו, האיורים, הטקסטים ועיצוב האתר שייכים ל־Browslium LLC או לבעלי הזכויות המתאימים. אפשר לקרוא באתר ולשתף קישור אליו. אין להציג מידע מטעה על הפרויקט, להתחזות ל־Browslium או להפריע לפעולת האתר.'],
        ['תרומות מרצון','כפתור התמיכה מוביל לעמוד Stripe שבו בוחרים סכום חד־פעמי. התרומה היא מרצון ואינה קונה מוצר, מנוי, גישה מועדפת או תוצאה מובטחת. הקישור הנוכחי אינו מציע מסלול חודשי. התשלום והחזרים אפשריים כפופים לכללים החלים בעמוד התשלום וב־Stripe.'],
        ['אין הבטחה להטבת מס','Browslium אינה מצהירה שתרומה מזכה בהטבת מס. הטיפול המסויי תלוי בנסיבות התורם ובתחום השיפוט שלו; במקרה הצורך פנו לייעוץ עצמאי.'],
        ['שירותים חיצוניים','ל־Stripe ולאתרים חיצוניים אחרים המקושרים מכאן יש תנאים וכללי פרטיות משלהם. איננו שולטים באתרים אחרים ואיננו אחראים לפעולתם או לתוכנם.'],
        ['דיוק ומגבלות','אנו משתדלים לעדכן את המידע, אך הפיתוח עשוי להשתנות. סינון אוטומטי עלול לטעות, והאתר אינו מבטיח כיסוי, ביצועים או תאריך השקה. הכתוב כאן אינו מחליף הסכם מוצר עתידי, הודעת פרטיות או תנאים שיידרשו לפני הפעלת השירות. זכויות מחייבות לפי החוק נשמרות.'],
        ['יצירת קשר ושינויים','לשאלות על האתר או על תרומה כתבו ל־admin@browslium.com. אנו עשויים לעדכן את התנאים עם התקדמות הפרויקט ונציג תאריך פרסום חדש בשינויים מהותיים.'],
      ],
    },
  },
  yi: {
    privacy: {
      title:'פּריוואַטקייט־פּאָליטיק',
      description:'ווי דער Browslium־וועבזײַט ניצט שפּראַך־אײַנשטעלונגען, באַהאַנדלט אימעיל און שיקט צו Stripe פֿאַר פֿרײַוויליקע בײַשטײַערן.',
      intro:'די פּאָליטיק גילט פֿאַרן עפֿנטלעכן Browslium־וועבזײַט. דער פילטער־דינסט איז נאָך אין אַנטוויקלונג און פּרוּוון; דער וועבזײַט אַליין קאָנטראָלירט נישט וואָס איר זעט אויף אַנדערע וועבזײַטן.',
      updated:'פֿאַרעפֿנטלעכט דעם 6טן אָקטאָבער 2026',
      sections:[
        ['ווער מיר זענען','Browslium LLC פֿירט דעם וועבזײַט. פֿאַר אַ פּריוואַטקייט־פֿראַגע אָדער בקשה, שרײַבט צו admin@browslium.com.'],
        ['בײַם באַזוכן דעם וועבזײַט','דאָס איז אַ סטאַטישער וועבזײַט. מיר האָבן נישט אַרײַנגעשטעלט רעקלאַמע־נאָכפֿאָלגער אָדער אַן אויסווייניקן אַנאַליטיק־סקריפּט. דער האָסטינג־ליפֿעראַנט קען באַאַרבעטן טעכנישע דאַטן ווי אײַער IP־אַדרעס, בלעטערער, געפֿרעגטן בלאט און צײַט כּדי צו ווײַזן און באַשיצן דעם וועבזײַט. דער וועבזײַט אַנאַליזירט נישט דעם אינהאַלט פֿון אַנדערע זײַטן וואָס איר באַזוכט.'],
        ['שפּראַך־אויסוואַל','דער וועבזײַט לייענט די שפּראַכן פֿון אײַער בלעטערער כּדי איין מאָל צו פֿאָרשלאָגן אַ שפּראַך. אויב איר קלײַבט אַ שפּראַך, ווערט דאָס געהיט אינעם לאָקאַלן סטאָרידזש פֿונעם בלעטערער און באַקומט פֿאָררעכט בײַ שפּעטערדיקע באַזוכן. אויך דאָס פֿאַרמאַכן פֿונעם פֿאָרשלאָג ווערט געהיט נאָר לאָקאַל. די שפּראַך־פונקציע שיקט די אײַנשטעלונגען נישט צו Browslium. מע קען זיי אויסמעקן אין די בלעטערער־אײַנשטעלונגען פֿאַר וועבזײַט־דאַטן.'],
        ['קאָנטאַקט דורך אימעיל','דער קאָנטאַקט־לינק עפֿנט אײַער אייגענע אימעיל־אַפּליקאַציע. אויב איר שרײַבט אונדז, באַקומן מיר אײַער אַדרעס און די פּרטים וואָס איר שיקט. שיקט נישט קיין פּאַראָלן, קאָרט־נומערן אָדער אַנדערע שפּירעוודיקע דאַטן. מיר ניצן דעם בריוו צו ענטפֿערן אָדער איבערקוקן די בקשה און קענען היטן די קאָרעספּאָנדענץ ווי לאַנג עס איז נייטיק פֿאַר דעם ציל אָדער לויט געזעץ. וועגן צוטריט אָדער אויסמעקן קען מען שרײַבן צום זעלבן אַדרעס.'],
        ['פֿרײַוויליקע בײַשטײַערן','דער בײַשטײַער־קנעפּל עפֿנט אַ צאָלונגס־זײַט פֿון Stripe. Stripe באַהאַנדלט קאָרט־דאַטן לויט אירע אייגענע פּריוואַטקייט־כללים. דער וועבזײַט נעמט אָדער היט נישט קיין קאָרט־פּרטים. Browslium קען באַקומן בײַשטײַער־רעקאָרדן און קאָנטאַקט־פּרטים וואָס Stripe גיט דעם חשבון־אייגנטימער פֿאַר פֿירן בײַשטײַערן, בוכהאַלטונג אָדער נייטיקע רעקאָרדן. אַ בײַשטײַער קויפֿט נישט קיין צוטריט צום פּראָדוקט.'],
        ['דער צוקונפֿטיקער פילטער־דינסט','דער פּלאַנירטער פּראָדוקט דאַרף אַנאַליזירן געשטיצטן אינהאַלט כּדי צו באַשליסן ווי צו פֿילטערן. דער וועבזײַט שטעלט דאָס נישט אָן. פֿאַרן אַלגעמיינעם אַרויסלאָז וועלן מיר באַזונדער פֿאַרעפֿנטלעכן פּינקטלעכע פּרטים וועגן דאַטן־וועגן, אויפֿהיטן, זיכערקייט און באַניצער־אויסוואַל לויט דער אמתער פּראָדוקציע־סיסטעם. מיר זאָגן נישט אַז דער צוקונפֿטיקער דינסט באַאַרבעט אָדער היט גאָרנישט.'],
        ['בקשות, זיכערקייט און ענדערונגען','איר קענט זיך ווענדן צו אונדז וועגן דאַטן וואָס איר האָט געשיקט דורך אימעיל אָדער אַ בײַשטײַער. מיר קענען דאַרפֿן באַשטעטיקן די בקשה און היטן רעקאָרדן וואָס געזעץ פֿאָדערט. האָסטינג־, אימעיל־ אָדער צאָלונגס־ליפֿעראַנטן קענען באַאַרבעטן דאַטן אין אַנדערע לענדער. קיין וועבזײַט קען נישט צוזאָגן אַבסאָלוטע זיכערקייט. בײַ וויכטיקע ענדערונגען וועלן מיר דערהײַנטיקן דעם דאַטום און דעם טעקסט.'],
      ],
    },
    terms: {
      title:'באַנוץ־תּנאָים פֿונעם וועבזײַט',
      description:'תּנאָים פֿאַרן Browslium־אינפֿאָרמאַציע־וועבזײַט און פֿרײַוויליקע בײַשטײַערן דורך Stripe.',
      intro:'די תּנאָים גילטן פֿאַרן עפֿנטלעכן וועבזײַט. Browslium איז אין אַנטוויקלונג; דער וועבזײַט מעלדט נישט אָן מיטלען, גיט נישט קיין פּראָדוקציע־פילטער־חשבון און שאַפֿט נישט קיין אַבאָנעמענט.',
      updated:'פֿאַרעפֿנטלעכט דעם 6טן אָקטאָבער 2026',
      sections:[
        ['וועגן דעם וועבזײַט','Browslium LLC פֿאַרעפֿנטלעכט אינפֿאָרמאַציע וועגן אַן אינהאַלט־פילטער אין אַנטוויקלונג און פּרוּוון. די באַשרײַבונגען פֿון כללים און פּלאַנירטע פונקציעס דערקלערן דעם פּלאַן און צוזאָגן נישט אַז עס אַרבעט אויף יעדן מיטל, אין יעדער אַפּליקאַציע אָדער בלעטערער. דער פּלאַטפאָרמע־מצב איז אַן אַנטוויקלונג־באַריכט, נישט קיין צוזאָג פֿון באַלדיקן צוטריט.'],
        ['ניצן דעם אינהאַלט','דער נאָמען Browslium, דער לאָגאָ, די בילדער, טעקסטן און וועבזײַט־אויסזען געהערן צו Browslium LLC אָדער די פּאַסיקע רעכט־אייגנטימער. איר קענט לייענען און טיילן אַ לינק צום וועבזײַט. מע טאָר נישט פֿאַלש פֿאָרשטעלן דעם פּראָיעקט, זיך אויסגעבן פֿאַר Browslium אָדער שטערן דעם וועבזײַט.'],
        ['פֿרײַוויליקע בײַשטײַערן','דער הילף־קנעפּל פֿירט צו אַ Stripe־זײַט וווּ איר קלײַבט אַ איין־מאָליקן סכום. אַ בײַשטײַער איז פֿרײַוויליק און קויפֿט נישט קיין פּראָדוקט, אַבאָנעמענט, בעסערן צוטריט אָדער גאַראַנטירטן רעזולטאַט. דער איצטיקער לינק האָט נישט קיין חודשלעכן פּלאַן. צאָלונג און מעגלעכע צוריקצאָלונגען גייען לויט די פּאַסיקע כּללים פֿון Stripe און איר צאָלונגס־זײַט.'],
        ['קיין שטײַער־צוזאָג','Browslium זאָגט נישט אַז אַ בײַשטײַער גיט אַ שטײַער־אָפּצוג. דאָס ווענדט זיך אָן אין אײַער מצב און לאַנד; בעט אומאָפּהענגיקע עצה אויב נייטיק.'],
        ['אויסווייניקע דינסטן','Stripe און אַנדערע אויסווייניקע זײַטן וואָס מיר פֿאַרבינדן האָבן אייגענע תּנאָים און פּריוואַטקייט־כללים. מיר קאָנטראָלירן נישט זייער אַרבעט אָדער אינהאַלט.'],
        ['ריכטיקייט און גרענעצן','מיר פּרוּוון צו האַלטן די אינפֿאָרמאַציע אַקטועל, אָבער די אַנטוויקלונג קען זיך טוישן. אַן אויטאָמאַטישער פילטער קען זיך טעותן, און דער וועבזײַט צוזאָגט נישט קיין דעקונג, שנעלקייט אָדער אַרויסלאָז־דאַטום. דאָס פֿאַרבײַט נישט קיין צוקונפֿטיקן פּראָדוקט־הסכם, פּריוואַטקייט־ידיעה אָדער געזעצלעך נייטיקע תּנאָים פֿאַרן אַקטיווירן אַ דינסט. מחויבֿדיקע געזעצלעכע רעכטן בלײַבן.'],
        ['קאָנטאַקט און ענדערונגען','פֿראַגעס וועגן דעם וועבזײַט אָדער אַ בײַשטײַער שיקט צו admin@browslium.com. מיר קענען דערהײַנטיקן די תּנאָים מיטן פּראָיעקט און ווײַזן אַ נײַעם פֿאַרעפֿנטלעכונג־דאַטום בײַ וויכטיקע ענדערונגען.'],
      ],
    },
  },
  'pt-BR': {
    privacy: {
      title:'Política de Privacidade',
      description:'Como o site do Browslium usa a preferência de idioma, recebe e-mails e direciona ao Stripe para contribuições voluntárias.',
      intro:'Esta política cobre o site público do Browslium. O serviço de filtragem está em desenvolvimento e testes; este site não inspeciona o conteúdo da sua navegação em outros sites.',
      updated:'Publicada em 6 de outubro de 2026',
      sections:[
        ['Quem somos','A Browslium LLC opera este site. Para dúvidas ou solicitações de privacidade, escreva para admin@browslium.com.'],
        ['Navegação no site','Este é um site estático. Não instalamos rastreadores de publicidade nem scripts de análise de terceiros. O provedor de hospedagem pode processar dados técnicos, como endereço IP, navegador, página solicitada e horário, para entregar e proteger o site. Este site não examina o conteúdo de outros sites que você acessa.'],
        ['Preferência de idioma','O site consulta os idiomas do navegador para sugerir uma opção uma única vez. Se você escolher um idioma, a preferência ficará no armazenamento local do navegador e terá prioridade nas próximas visitas. Dispensar a sugestão também é salvo localmente. O recurso de idioma não envia essas escolhas ao Browslium. Você pode apagá-las nas configurações de dados de sites do navegador.'],
        ['Contato por e-mail','O link de contato abre seu próprio aplicativo de e-mail. Se você nos escrever, receberemos seu endereço e as informações que decidir enviar. Evite senhas, números de cartão e outros dados sensíveis. Usamos a mensagem para responder ou analisar sua solicitação e podemos guardar a conversa enquanto for necessário para isso ou por obrigação legal. Solicitações de acesso ou exclusão podem ser feitas no mesmo endereço.'],
        ['Contribuições voluntárias','O botão de contribuição abre uma página de pagamento hospedada pelo Stripe. O Stripe trata os dados do cartão conforme suas próprias regras de privacidade. Este site não coleta nem armazena dados do cartão. O Browslium pode receber registros de contribuições e dados de contato que o Stripe disponibiliza ao titular da conta para administrar contribuições, contabilidade e registros obrigatórios. Contribuir não compra acesso ao produto.'],
        ['Futuro serviço de filtragem','O produto planejado precisa analisar conteúdo compatível para tomar decisões de filtragem. Este site não ativa esse processamento. Antes do acesso geral ao serviço, publicaremos informações separadas e precisas sobre fluxos de dados, retenção, segurança e escolhas dos usuários com base no sistema de produção. Não afirmamos que o futuro serviço não processará nem armazenará dados.'],
        ['Solicitações, segurança e mudanças','Você pode falar conosco sobre informações enviadas por e-mail ou em uma contribuição. Talvez precisemos verificar a solicitação e manter registros exigidos por lei. Provedores de hospedagem, e-mail ou pagamento podem tratar dados em outros países. Nenhum site garante segurança absoluta. Se esta política mudar de maneira relevante, atualizaremos a data e o conteúdo.'],
      ],
    },
    terms: {
      title:'Termos do site',
      description:'Condições de uso do site informativo do Browslium e de contribuições voluntárias pelo Stripe.',
      intro:'Estes termos se aplicam ao site público. O Browslium está em desenvolvimento: o site não inscreve dispositivos, não fornece uma conta de filtragem em produção e não cria uma assinatura do serviço.',
      updated:'Publicados em 6 de outubro de 2026',
      sections:[
        ['Sobre este site','A Browslium LLC publica informações sobre um sistema de filtragem de conteúdo em desenvolvimento e testes. Descrições de políticas e recursos planejados explicam o projeto e não prometem que algo já funcione em todos os dispositivos, apps ou navegadores. O status das plataformas é uma atualização de desenvolvimento, não uma oferta de acesso imediato.'],
        ['Uso do conteúdo','O nome Browslium, logotipo, ilustrações, textos e design pertencem à Browslium LLC ou aos respectivos titulares. Você pode ler o site e compartilhar seu link. Não deturpe o projeto, não se passe pelo Browslium nem interfira no funcionamento do site.'],
        ['Contribuições voluntárias','O botão de apoio leva a uma página do Stripe onde você escolhe um valor único. A contribuição é voluntária e não compra produto, assinatura, acesso preferencial nem resultado garantido. O link atual não oferece plano mensal. O pagamento e eventuais reembolsos seguem as regras aplicáveis da página de pagamento e do Stripe.'],
        ['Sem promessa de dedução fiscal','O Browslium não afirma que uma contribuição seja dedutível de impostos. O tratamento tributário depende das circunstâncias e da jurisdição de quem contribui; procure orientação independente se necessário.'],
        ['Serviços externos','O Stripe e outros destinos externos vinculados ao site têm regras próprias de uso e privacidade. Não controlamos nem respondemos pelo funcionamento ou conteúdo de sites de terceiros.'],
        ['Precisão e limites','Procuramos manter as informações atualizadas, mas o desenvolvimento pode mudar. A filtragem automática pode errar e este site não garante cobertura, desempenho nem data de lançamento. Nada aqui substitui um futuro contrato de produto, aviso de privacidade ou termos exigidos por lei antes da ativação do serviço. Direitos obrigatórios da lei aplicável continuam válidos.'],
        ['Contato e alterações','Para dúvidas sobre o site ou uma contribuição, escreva para admin@browslium.com. Podemos atualizar estes termos conforme o projeto avança e mostraremos uma nova data de publicação em mudanças relevantes.'],
      ],
    },
  },
  fr: {
    privacy: {
      title:'Politique de confidentialité',
      description:'Comment le site Browslium utilise la préférence de langue, reçoit les e-mails et renvoie vers Stripe pour les contributions volontaires.',
      intro:'Cette politique concerne le site public de Browslium. Le service de filtrage est en développement et en test ; ce site n’inspecte pas le contenu de votre navigation sur d’autres sites.',
      updated:'Publiée le 6 octobre 2026',
      sections:[
        ['Qui sommes-nous ?','Browslium LLC exploite ce site. Pour toute question ou demande relative à la confidentialité, écrivez à admin@browslium.com.'],
        ['Visite du site','Ce site est statique. Nous n’y avons installé ni traceur publicitaire ni script d’analyse tiers. L’hébergeur peut traiter des données techniques, comme votre adresse IP, votre navigateur, la page demandée et l’heure, pour fournir et protéger le site. Ce site n’examine pas le contenu des autres sites que vous visitez.'],
        ['Préférence de langue','Le site lit les langues configurées dans votre navigateur pour proposer une langue une seule fois. Si vous choisissez une langue, ce choix est enregistré dans le stockage local du navigateur et prime lors de vos prochaines visites. Le fait de fermer la suggestion est aussi conservé localement. Cette fonction n’envoie pas ces réglages à Browslium. Vous pouvez les supprimer dans les paramètres de données des sites de votre navigateur.'],
        ['Contact par e-mail','Le lien de contact ouvre votre propre logiciel de messagerie. Si vous nous écrivez, nous recevons votre adresse et les informations que vous choisissez d’envoyer. Évitez mots de passe, numéros de carte et autres données sensibles. Nous utilisons le message pour répondre ou étudier votre demande et pouvons conserver la correspondance tant que cela est nécessaire ou imposé par la loi. Vous pouvez demander l’accès ou l’effacement à la même adresse.'],
        ['Contributions volontaires','Le bouton de contribution ouvre une page de paiement hébergée par Stripe. Stripe traite les données de carte selon ses propres règles de confidentialité. Ce site ne collecte ni ne conserve ces données. Browslium peut recevoir les informations sur les contributions et les contacts que Stripe met à la disposition du titulaire du compte pour gérer les contributions, la comptabilité ou les registres requis. Une contribution n’achète pas l’accès au produit.'],
        ['Futur service de filtrage','Le produit envisagé doit analyser les contenus compatibles pour prendre des décisions de filtrage. Ce site n’active pas ce traitement. Avant un accès général au service, nous publierons des informations distinctes et exactes sur les flux de données, leur conservation, la sécurité et les choix des utilisateurs, fondées sur le système réellement exploité. Nous n’affirmons pas que le futur service ne traitera ou ne conservera rien.'],
        ['Demandes, sécurité et modifications','Vous pouvez nous contacter à propos des informations envoyées par e-mail ou lors d’une contribution. Nous pouvons devoir vérifier une demande et conserver des registres exigés par la loi. Les prestataires d’hébergement, d’e-mail ou de paiement peuvent traiter des données dans d’autres pays. Aucun site ne peut garantir une sécurité absolue. Si cette politique change de manière importante, nous mettrons à jour sa date et son contenu.'],
      ],
    },
    terms: {
      title:'Conditions du site',
      description:'Conditions d’utilisation du site d’information Browslium et des contributions volontaires via Stripe.',
      intro:'Ces conditions s’appliquent au site public. Browslium est en développement : le site n’inscrit pas d’appareil, ne fournit pas de compte de filtrage en production et ne crée pas d’abonnement au service.',
      updated:'Publiées le 6 octobre 2026',
      sections:[
        ['À propos du site','Browslium LLC publie des informations sur un système de filtrage de contenu en développement et en test. La présentation des règles et fonctions envisagées explique le projet sans promettre leur disponibilité sur tous les appareils, applications ou navigateurs. L’état des plateformes est un point d’avancement, pas une offre d’accès immédiat.'],
        ['Utilisation des contenus','Le nom Browslium, le logo, les illustrations, les textes et le design appartiennent à Browslium LLC ou à leurs titulaires respectifs. Vous pouvez lire le site et en partager le lien. Ne présentez pas le projet de manière trompeuse, ne vous faites pas passer pour Browslium et ne perturbez pas le site.'],
        ['Contributions volontaires','Le bouton de soutien mène à une page Stripe où vous choisissez un montant ponctuel. La contribution est volontaire et n’achète ni produit, ni abonnement, ni accès prioritaire, ni résultat garanti. Le lien actuel ne propose pas de formule mensuelle. Le paiement et les remboursements éventuels suivent les règles applicables de la page de paiement et de Stripe.'],
        ['Aucun avantage fiscal promis','Browslium n’affirme pas qu’une contribution ouvre droit à une déduction fiscale. Le traitement fiscal dépend de votre situation et de votre pays ; demandez un conseil indépendant si nécessaire.'],
        ['Services externes','Stripe et les autres destinations externes liées depuis ce site ont leurs propres conditions et pratiques de confidentialité. Nous ne contrôlons pas les sites tiers et ne répondons pas de leur fonctionnement ou de leur contenu.'],
        ['Exactitude et limites','Nous tâchons de garder les informations à jour, mais le développement peut évoluer. Le filtrage automatique peut se tromper et ce site ne garantit ni couverture, ni performance, ni date de lancement. Rien ici ne remplace un futur contrat de produit, avis de confidentialité ou conditions légalement requises avant activation du service. Les droits impératifs restent applicables.'],
        ['Contact et modifications','Pour toute question sur le site ou une contribution, écrivez à admin@browslium.com. Nous pouvons mettre à jour ces conditions avec l’avancement du projet et afficherons une nouvelle date de publication en cas de changement important.'],
      ],
    },
  },
};
