// Editorial policy definitions supplied by the project owner on 2026-10-06.
// These are design rules, not assertions about current production availability.
export const policies = {
  en: {
    image: [
      'Mask visible features of women while leaving clothing visible.',
      'Mask women completely.',
      'Mask women and women’s clothing completely.',
      'Mask women completely and alter the remaining shape.',
      'Mask women and women’s clothing, with shape alteration.',
      'Block an entire image when it contains women.',
      'Block an entire image when it contains women or women’s clothing.',
    ],
    video: [
      'Mask women completely in the video.',
      'Mask women and women’s clothing completely in the video.',
      'Mask women and alter the remaining shape in the video.',
      'Mask women and women’s clothing, with shape alteration in the video.',
      'Block the entire video when it contains women.',
      'Block the entire video when it contains women or women’s clothing.',
    ],
  },
  es: {
    image: [
      'Cubrir los rasgos visibles de las mujeres y conservar visible la ropa.',
      'Cubrir por completo a las mujeres.',
      'Cubrir por completo a las mujeres y la ropa de mujer.',
      'Cubrir por completo a las mujeres y alterar la forma restante.',
      'Cubrir a las mujeres y la ropa de mujer, con alteración de la forma.',
      'Bloquear la imagen completa si contiene mujeres.',
      'Bloquear la imagen completa si contiene mujeres o ropa de mujer.',
    ],
    video: [
      'Cubrir por completo a las mujeres en el video.',
      'Cubrir por completo a las mujeres y la ropa de mujer en el video.',
      'Cubrir a las mujeres y alterar la forma restante en el video.',
      'Cubrir a las mujeres y la ropa de mujer, con alteración de la forma en el video.',
      'Bloquear el video completo si contiene mujeres.',
      'Bloquear el video completo si contiene mujeres o ropa de mujer.',
    ],
  },
  ru: {
    image: [
      'Скрывать видимые черты женщин, оставляя одежду видимой.',
      'Полностью скрывать женщин.',
      'Полностью скрывать женщин и женскую одежду.',
      'Полностью скрывать женщин с изменением оставшегося контура.',
      'Скрывать женщин и женскую одежду с изменением контура.',
      'Блокировать изображение целиком, если на нём есть женщины.',
      'Блокировать изображение целиком, если на нём есть женщины или женская одежда.',
    ],
    video: [
      'Полностью скрывать женщин в видео.',
      'Полностью скрывать женщин и женскую одежду в видео.',
      'Скрывать женщин с изменением оставшегося контура в видео.',
      'Скрывать женщин и женскую одежду с изменением контура в видео.',
      'Блокировать видео целиком, если в нём есть женщины.',
      'Блокировать видео целиком, если в нём есть женщины или женская одежда.',
    ],
  },
  he: {
    image: [
      'להסתיר מאפיינים גלויים של נשים ולהשאיר את הבגדים גלויים.',
      'להסתיר נשים לחלוטין.',
      'להסתיר לחלוטין נשים ובגדי נשים.',
      'להסתיר נשים לחלוטין ולשנות את הצורה שנותרה.',
      'להסתיר נשים ובגדי נשים תוך שינוי הצורה.',
      'לחסום את התמונה כולה אם מופיעות בה נשים.',
      'לחסום את התמונה כולה אם מופיעות בה נשים או בגדי נשים.',
    ],
    video: [
      'להסתיר נשים לחלוטין בווידאו.',
      'להסתיר לחלוטין נשים ובגדי נשים בווידאו.',
      'להסתיר נשים ולשנות את הצורה שנותרה בווידאו.',
      'להסתיר נשים ובגדי נשים תוך שינוי הצורה בווידאו.',
      'לחסום את הסרטון כולו אם מופיעות בו נשים.',
      'לחסום את הסרטון כולו אם מופיעות בו נשים או בגדי נשים.',
    ],
  },
  yi: {
    image: [
      'פֿאַרדעקן די זעבאַרע שטריכן פֿון פֿרויען, אָבער לאָזן די קליידער זעבאַר.',
      'פֿאַרדעקן פֿרויען אין גאַנצן.',
      'פֿאַרדעקן פֿרויען און פֿרויען־קליידער אין גאַנצן.',
      'פֿאַרדעקן פֿרויען אין גאַנצן און פֿאַרענדערן די איבערגעבליבענע פֿאָרעם.',
      'פֿאַרדעקן פֿרויען און פֿרויען־קליידער מיט אַ פֿאַרענדערטער פֿאָרעם.',
      'בלאָקירן דעם גאַנצן בילד אויב עס זענען דאָ פֿרויען.',
      'בלאָקירן דעם גאַנצן בילד אויב עס זענען דאָ פֿרויען אָדער פֿרויען־קליידער.',
    ],
    video: [
      'פֿאַרדעקן פֿרויען אין גאַנצן אינעם ווידעאָ.',
      'פֿאַרדעקן פֿרויען און פֿרויען־קליידער אין גאַנצן אינעם ווידעאָ.',
      'פֿאַרדעקן פֿרויען און פֿאַרענדערן די איבערגעבליבענע פֿאָרעם אינעם ווידעאָ.',
      'פֿאַרדעקן פֿרויען און פֿרויען־קליידער מיט אַ פֿאַרענדערטער פֿאָרעם אינעם ווידעאָ.',
      'בלאָקירן דעם גאַנצן ווידעאָ אויב עס זענען דאָ פֿרויען.',
      'בלאָקירן דעם גאַנצן ווידעאָ אויב עס זענען דאָ פֿרויען אָדער פֿרויען־קליידער.',
    ],
  },
  'pt-BR': {
    image: [
      'Cobrir características visíveis de mulheres, mantendo as roupas visíveis.',
      'Cobrir completamente as mulheres.',
      'Cobrir completamente as mulheres e as roupas femininas.',
      'Cobrir completamente as mulheres e alterar o contorno restante.',
      'Cobrir as mulheres e as roupas femininas, alterando o contorno.',
      'Bloquear a imagem inteira quando houver mulheres.',
      'Bloquear a imagem inteira quando houver mulheres ou roupas femininas.',
    ],
    video: [
      'Cobrir completamente as mulheres no vídeo.',
      'Cobrir completamente as mulheres e as roupas femininas no vídeo.',
      'Cobrir as mulheres e alterar o contorno restante no vídeo.',
      'Cobrir as mulheres e as roupas femininas, alterando o contorno no vídeo.',
      'Bloquear o vídeo inteiro quando houver mulheres.',
      'Bloquear o vídeo inteiro quando houver mulheres ou roupas femininas.',
    ],
  },
  fr: {
    image: [
      'Masquer les traits visibles des femmes tout en laissant les vêtements visibles.',
      'Masquer entièrement les femmes.',
      'Masquer entièrement les femmes et les vêtements féminins.',
      'Masquer entièrement les femmes et modifier la forme restante.',
      'Masquer les femmes et les vêtements féminins en modifiant la forme.',
      'Bloquer l’image entière lorsqu’elle contient des femmes.',
      'Bloquer l’image entière lorsqu’elle contient des femmes ou des vêtements féminins.',
    ],
    video: [
      'Masquer entièrement les femmes dans la vidéo.',
      'Masquer entièrement les femmes et les vêtements féminins dans la vidéo.',
      'Masquer les femmes et modifier la forme restante dans la vidéo.',
      'Masquer les femmes et les vêtements féminins en modifiant la forme dans la vidéo.',
      'Bloquer la vidéo entière lorsqu’elle contient des femmes.',
      'Bloquer la vidéo entière lorsqu’elle contient des femmes ou des vêtements féminins.',
    ],
  },
};
