// Product account and device notice. Keep the published website policy in legal.mjs separate.
// Review this text against the deployed service before enabling general registration.
export const productPrivacy = {
  en: {
    title: 'Product Privacy Notice',
    description: 'How Browslium handles account, device, policy, support and payment information for its product.',
    intro: 'This notice describes the Browslium product account, portal and managed-device features when they are enabled. It is separate from the privacy policy for this informational website. Features and data flows may differ by device and development stage.',
    updated: 'Published October 9, 2026',
    websitePolicy: 'Privacy policy for this website',
    sections: [
      ['Who is responsible', 'Browslium LLC, 30 N Gould St, Sheridan, WY 82801, USA, is the contact for this product notice. Send privacy questions or requests to admin@browslium.com.'],
      ['Who can hold an account', 'Product accounts are for adults only. Registration asks the person creating an account to declare that they are an adult; it does not currently use an age-verification service. Acknowledging receipt of this notice is distinct from any optional consent, which must be requested separately when needed. An adult may manage a device used by another person only with the required ownership, authority and permissions. Browslium does not offer accounts to minors. If you believe a minor created an account, contact us so we can review and take appropriate action.'],
      ['Account and identity data', 'For account creation and sign-in, we may handle your name, email address, account identifiers, organization or role, authentication events and session data. If you choose Google or Microsoft sign-in, the identity provider sends the information needed to identify your account through OpenID Connect. Its own privacy terms also apply to its service. Do not send us your Google or Microsoft password.'],
      ['Devices, settings and requests', 'When an adult enrolls or manages an authorized device, the product may handle device identifiers and technical characteristics, enrollment and connection status, software version, assigned policies, per-device settings, administrative actions, exception requests and their outcomes. Device management may involve information about a device user other than the account holder. The account holder must have the appropriate authority to configure that device and inform affected people as required.'],
      ['Filtering and technical data', 'Filtering supported content requires analysis to decide which selected policy applies. Depending on the device, feature and deployment, this may involve content or derived signals, URLs or categories, decision results, error reports and security logs. Do not assume that content is never transmitted or retained. We will update this notice with verified feature-specific processing and retention details before general service access.'],
      ['Payments and messages', 'If payment setup is offered, Stripe handles payment-card entry and storage through its own interface. Browslium may receive customer, payment-method reference, setup or billing status and transaction records needed to administer the account. We do not ask you to enter full card numbers in the Browslium portal. Service messages may be sent through Resend; we process the recipient address, message and delivery information needed for those communications. If you contact support, we receive what you choose to send.'],
      ['Why we use information', 'We use the information described above to provide sign-in and account access, enroll and administer authorized devices, apply selected filtering policies, respond to exceptions and support requests, communicate about the service, administer payment setup and billing where available, protect the service, investigate errors and meet applicable recordkeeping obligations. We do not describe the product as having no data processing.'],
      ['Service providers and locations', 'Google and Microsoft may provide sign-in, Resend may deliver email, Stripe may process payment setup or payments, and DigitalOcean may host service infrastructure. Each receives information relevant to its role. Processing may occur outside your country, including in the United States. Additional integrations or locations must be disclosed when actually enabled; this notice does not claim a verified international transfer mechanism for every jurisdiction.'],
      ['Retention and security', 'The data needed to operate an account or managed device, respond to requests, secure the service and satisfy applicable records duties may be retained for different periods. Exact schedules, backup behavior and feature-specific retention remain to be verified against the deployed system and will be published before general service access. We use access controls and other safeguards appropriate to the implemented service, but no system can promise absolute security.'],
      ['Your choices and requests', 'Account holders can choose supported policies and manage authorized devices and settings where the feature is available. For access, correction, deletion or another privacy request, email admin@browslium.com. We may need to verify identity and authority, and some information may need to be retained where required or permitted by applicable law. Available rights depend on your location and the circumstances.'],
      ['Changes and scope', 'We will revise the publication date and this notice when material product data practices change. This page describes the product; the separate website policy covers visits to browslium.com and voluntary contributions made through the informational site. Publication of this notice does not mean every product feature is generally available.'],
    ],
  },
  es: {
    title: 'Aviso de privacidad del producto',
    description: 'Cómo Browslium trata datos de cuentas, dispositivos, políticas, soporte y pagos de su producto.',
    intro: 'Este aviso describe las cuentas, el portal y la gestión de dispositivos del producto Browslium cuando esas funciones están habilitadas. Es distinto de la política de privacidad de esta web informativa. Las funciones y los flujos de datos pueden variar según el dispositivo y la etapa de desarrollo.',
    updated: 'Publicado el 9 de octubre de 2026',
    websitePolicy: 'Política de privacidad de esta web',
    sections: [
      ['Responsable y contacto', 'Browslium LLC, 30 N Gould St, Sheridan, WY 82801, Estados Unidos, es el contacto para este aviso del producto. Envía consultas o solicitudes de privacidad a admin@browslium.com.'],
      ['Quién puede tener una cuenta', 'Las cuentas del producto son sólo para adultos. Al registrarse, la persona declara que es adulta; actualmente no se utiliza un servicio de verificación de edad. Acusar recibo de este aviso es distinto de otorgar un consentimiento opcional, que debe solicitarse por separado cuando sea necesario. Un adulto puede administrar un dispositivo usado por otra persona sólo si cuenta con la propiedad, autorización y permisos necesarios. Browslium no ofrece cuentas a menores. Si crees que un menor creó una cuenta, avísanos para que revisemos el caso y tomemos las medidas adecuadas.'],
      ['Datos de cuenta e identidad', 'Para crear una cuenta e iniciar sesión, podemos tratar nombre, correo electrónico, identificadores de cuenta, organización o función, eventos de autenticación y datos de sesión. Si eliges iniciar sesión con Google o Microsoft, ese proveedor envía mediante OpenID Connect los datos necesarios para identificar tu cuenta. Su servicio también se rige por sus propias condiciones de privacidad. No nos envíes tu contraseña de Google o Microsoft.'],
      ['Dispositivos, ajustes y solicitudes', 'Cuando un adulto inscribe o administra un dispositivo autorizado, el producto puede tratar identificadores y características técnicas del dispositivo, estado de inscripción y conexión, versión de software, políticas asignadas, ajustes por dispositivo, acciones administrativas, solicitudes de excepción y sus resultados. La gestión puede incluir datos de una persona que usa el dispositivo sin ser titular de la cuenta. El titular debe tener la autorización adecuada para configurarlo e informar a las personas afectadas cuando corresponda.'],
      ['Filtrado y datos técnicos', 'Filtrar contenido compatible requiere analizarlo para decidir cómo aplicar la política seleccionada. Según el dispositivo, la función y el despliegue, esto puede incluir contenido o señales derivadas, URL o categorías, resultados de decisiones, informes de errores y registros de seguridad. No presupongas que el contenido nunca se transmite o conserva. Actualizaremos este aviso con detalles verificados por función sobre el tratamiento y la conservación antes del acceso general al servicio.'],
      ['Pagos y mensajes', 'Si se ofrece el registro de un método de pago, Stripe recibe y almacena los datos de tarjeta mediante su propia interfaz. Browslium puede recibir referencias del cliente y método de pago, estado de configuración o facturación y registros de transacciones necesarios para administrar la cuenta. No te pedimos introducir el número completo de tarjeta en el portal de Browslium. Los mensajes del servicio pueden enviarse mediante Resend; tratamos la dirección de destino, el mensaje y los datos de entrega necesarios. Si contactas a soporte, recibimos la información que decidas enviar.'],
      ['Para qué usamos los datos', 'Usamos los datos descritos para ofrecer acceso a la cuenta, inscribir y administrar dispositivos autorizados, aplicar políticas de filtrado elegidas, responder solicitudes de excepción y soporte, comunicarnos sobre el servicio, administrar el registro de pagos y la facturación cuando estén disponibles, proteger el servicio, investigar errores y cumplir obligaciones de registro aplicables. No afirmamos que el producto no trate datos.'],
      ['Proveedores y ubicaciones', 'Google y Microsoft pueden prestar el inicio de sesión; Resend, la entrega de correo; Stripe, el registro de pagos o cobros; y DigitalOcean, el alojamiento de infraestructura. Cada uno recibe datos pertinentes a su función. El tratamiento puede ocurrir fuera de tu país, incluso en Estados Unidos. Informaremos otras integraciones o ubicaciones cuando se habiliten; este aviso no afirma que se haya verificado un mecanismo de transferencia internacional para todas las jurisdicciones.'],
      ['Conservación y seguridad', 'Los datos necesarios para operar una cuenta o dispositivo administrado, atender solicitudes, proteger el servicio y cumplir obligaciones de registro pueden conservarse durante períodos distintos. Los plazos exactos, el funcionamiento de las copias de seguridad y la conservación por función aún deben verificarse frente al sistema desplegado y se publicarán antes del acceso general. Aplicamos controles de acceso y otras medidas apropiadas al servicio implementado, aunque ningún sistema garantiza seguridad absoluta.'],
      ['Opciones y solicitudes', 'Los titulares pueden elegir políticas compatibles y administrar dispositivos y ajustes autorizados donde la función esté disponible. Para solicitar acceso, corrección, eliminación u otra gestión de privacidad, escribe a admin@browslium.com. Puede ser necesario verificar tu identidad y autorización, y conservar ciertos datos cuando la ley aplicable lo exija o permita. Los derechos disponibles dependen de tu ubicación y circunstancias.'],
      ['Cambios y alcance', 'Actualizaremos la fecha de publicación y este aviso cuando cambien de forma importante las prácticas de datos del producto. Esta página describe el producto; la política separada de la web cubre las visitas a browslium.com y las aportaciones voluntarias hechas desde el sitio informativo. Publicar este aviso no significa que todas las funciones del producto estén disponibles de forma general.'],
    ],
  },
};
