// Copy for the same approved photo/video test galleries in all seven editions.
// These examples are controlled renders, not a claim of released filtering.
export const showcase = {
  en: {
    imageTitle: 'See what each image level changes',
    imageIntro: 'Start with an unfiltered photograph. Choose a scene and one of seven policies, then move the divider to compare the original with the test result.',
    videoTitle: 'Watch the six video policies',
    videoIntro: 'Choose a clip and a policy, then switch between the original and the test result. Levels 5 and 6 replace the whole clip with Browslium’s blocking video.',
    photoScenes: ['Colleagues', 'Clothes shopping', 'In the store'],
    photoAlts: ['Two colleagues standing outside an office', 'A woman browsing clothes in a store', 'A woman looking at a shirt in a store'],
    videoScenes: ['Shopping', 'Couple', 'Meeting'],
    videoAlts: ['A woman shopping in a store', 'A couple looking at a screen', 'Colleagues in a meeting'],
    scene: 'Choose a scene', policy: 'Choose a filtering level', original: 'Original', level: 'Level', before: 'Original', after: 'Filtered', drag: 'Drag to compare the original with the filtered result',
    originalImage: 'Original photograph. Select a level to compare it with a filtered test result.',
    originalVideo: 'Original clip. Select a level to watch its filtered test result.',
    result: 'Test result', playOriginal: 'Watch original', playFiltered: 'Watch filtered', loading: 'Loading preview…',
    imageNote: 'Controlled SAM 3.1 image tests. These examples do not establish general production availability.',
    videoNote: 'Silent clips from controlled project tests. Blocking videos use official localized brand media. These examples do not establish general production availability.',
    imageLink: 'Explore image filtering', videoLink: 'Explore video filtering',
  },
  es: {
    imageTitle: 'Mira qué cambia en cada nivel de imagen',
    imageIntro: 'Comienza con la foto original. Elige una escena y uno de los siete niveles; después mueve la línea para comparar el original con el resultado de la prueba.',
    videoTitle: 'Explora los seis niveles de vídeo',
    videoIntro: 'Elige un vídeo y una política. Alterna entre el original y el resultado de la prueba. Los niveles 5 y 6 sustituyen el vídeo completo por la pantalla de bloqueo de Browslium.',
    photoScenes: ['Colegas', 'De compras', 'En la tienda'],
    photoAlts: ['Dos colegas frente a un edificio de oficinas', 'Una mujer mira ropa en una tienda', 'Una mujer observa una camisa en una tienda'],
    videoScenes: ['De compras', 'Pareja', 'Reunión'],
    videoAlts: ['Una mujer compra en una tienda', 'Una pareja mira una pantalla', 'Colegas participan en una reunión'],
    scene: 'Elige una escena', policy: 'Elige un nivel de filtrado', original: 'Original', level: 'Nivel', before: 'Original', after: 'Filtrado', drag: 'Arrastra para comparar el original con el resultado filtrado',
    originalImage: 'Foto original. Elige un nivel para compararla con el resultado de la prueba.',
    originalVideo: 'Vídeo original. Elige un nivel para ver el resultado filtrado.',
    result: 'Resultado de la prueba', playOriginal: 'Ver original', playFiltered: 'Ver filtrado', loading: 'Cargando vista previa…',
    imageNote: 'Pruebas controladas de imágenes con SAM 3.1. Estos ejemplos no acreditan disponibilidad general en producción.',
    videoNote: 'Vídeos sin audio de pruebas controladas del proyecto. Los bloqueos usan los medios oficiales de marca en cada idioma. Estos ejemplos no acreditan disponibilidad general en producción.',
    imageLink: 'Conoce el filtrado de imágenes', videoLink: 'Conoce el filtrado de vídeo',
  },
  ru: {
    imageTitle: 'Как меняется изображение на каждом уровне',
    imageIntro: 'Сначала посмотрите исходное фото. Выберите сцену и один из семи уровней, затем передвиньте разделитель, чтобы сравнить оригинал с результатом теста.',
    videoTitle: 'Шесть уровней фильтрации видео',
    videoIntro: 'Выберите ролик и правило, затем переключайтесь между оригиналом и результатом теста. На уровнях 5 и 6 весь ролик заменяется фирменным экраном блокировки Browslium.',
    photoScenes: ['Коллеги', 'Выбор одежды', 'В магазине'],
    photoAlts: ['Двое коллег у офисного здания', 'Женщина выбирает одежду в магазине', 'Женщина рассматривает рубашку в магазине'],
    videoScenes: ['Покупки', 'Пара', 'Совещание'],
    videoAlts: ['Женщина делает покупки в магазине', 'Пара смотрит на экран', 'Коллеги на совещании'],
    scene: 'Выберите сцену', policy: 'Выберите уровень фильтрации', original: 'Оригинал', level: 'Уровень', before: 'Оригинал', after: 'После фильтрации', drag: 'Переместите ползунок для сравнения оригинала и результата фильтрации',
    originalImage: 'Исходное фото. Выберите уровень, чтобы сравнить его с результатом теста.',
    originalVideo: 'Исходный ролик. Выберите уровень, чтобы посмотреть результат фильтрации.',
    result: 'Результат теста', playOriginal: 'Смотреть оригинал', playFiltered: 'Смотреть после фильтрации', loading: 'Загрузка примера…',
    imageNote: 'Контролируемые тесты изображений с SAM 3.1. Примеры не подтверждают общую доступность функции в рабочем продукте.',
    videoNote: 'Ролики без звука из контролируемых тестов проекта. Для блокировки используются официальные видеоматериалы на соответствующем языке. Примеры не подтверждают общую доступность функции в рабочем продукте.',
    imageLink: 'Подробнее о фильтрации изображений', videoLink: 'Подробнее о фильтрации видео',
  },
  yi: {
    imageTitle: 'זעט וואָס יעדער בילד־ניוואָ ענדערט',
    imageIntro: 'קוקט ערשט אויפֿן אָריגינעלן פֿאָטאָ. קלײַבט אויס אַ סצענע און איינעם פֿון די זיבן ניוואָען, און רוקט דעם טיילער כּדי צו פֿאַרגלײַכן מיטן פּרוּוו־רעזולטאַט.',
    videoTitle: 'זעט די זעקס ווידעאָ־ניוואָען',
    videoIntro: 'קלײַבט אויס אַ קליפּ און אַ פּאָליטיק, און בײַט צווישן דעם אָריגינעל און דעם פּרוּוו־רעזולטאַט. אויף ניוואָען 5 און 6 ווערט דער גאַנצער קליפּ פֿאַרביטן מיטן Browslium־בלאָקירווידעאָ.',
    photoScenes: ['קאָלעגעס', 'קליידער קויפֿן', 'אין קראָם'],
    photoAlts: ['צוויי קאָלעגעס פֿאַר אַן אָפֿיס־בנין', 'אַ פֿרוי קוקט קליידער אין אַ קראָם', 'אַ פֿרוי קוקט אַ העמד אין אַ קראָם'],
    videoScenes: ['אײַנקויפֿן', 'פּאָרפֿאָלק', 'זיצונג'],
    videoAlts: ['אַ פֿרוי קויפֿט אײַן אין אַ קראָם', 'אַ פּאָר קוקט אויף אַן עקראַן', 'קאָלעגעס אין אַ זיצונג'],
    scene: 'קלײַבט אויס אַ סצענע', policy: 'קלײַבט אויס אַ פֿילטער־ניוואָ', original: 'אָריגינעל', level: 'ניוואָ', before: 'אָריגינעל', after: 'געפֿילטערט', drag: 'רוקט דעם טיילער צו פֿאַרגלײַכן דעם אָריגינעל מיטן געפֿילטערטן רעזולטאַט',
    originalImage: 'אָריגינעלער פֿאָטאָ. קלײַבט אַ ניוואָ צו פֿאַרגלײַכן מיטן פּרוּוו־רעזולטאַט.',
    originalVideo: 'אָריגינעלער קליפּ. קלײַבט אַ ניוואָ צו זען דעם געפֿילטערטן רעזולטאַט.',
    result: 'פּרוּוו־רעזולטאַט', playOriginal: 'זען אָריגינעל', playFiltered: 'זען געפֿילטערט', loading: 'דער בײַשפּיל ווערט געלאָדן…',
    imageNote: 'קאָנטראָלירטע בילד־פּרוּוון מיט SAM 3.1. די בײַשפּילן באַשטעטיקן נישט אַז די פֿונקציע איז שוין אַלגעמיין בנימצא.',
    videoNote: 'שטומע קליפּס פֿון קאָנטראָלירטע פּרוּוון פֿונעם פּראָיעקט. די בלאָקירווידעאָס זענען די אָפֿיציעלע מאַטעריאַלן אין יעדער שפּראַך. די בײַשפּילן באַשטעטיקן נישט אַלגעמיינע פֿאַרפֿיגבאַרקייט.',
    imageLink: 'מער וועגן בילד־פֿילטרירונג', videoLink: 'מער וועגן ווידעאָ־פֿילטרירונג',
  },
  he: {
    imageTitle: 'ראו מה משתנה בכל רמת סינון תמונות',
    imageIntro: 'מתחילים בתמונה המקורית. בוחרים סצנה ואחת משבע הרמות, ואז גוררים את קו ההפרדה כדי להשוות בין המקור לתוצאת הבדיקה.',
    videoTitle: 'צפו בשש רמות סינון הווידאו',
    videoIntro: 'בוחרים סרטון ומדיניות, ועוברים בין המקור לתוצאת הבדיקה. ברמות 5 ו־6 הסרטון כולו מוחלף בסרטון החסימה של Browslium.',
    photoScenes: ['עמיתים לעבודה', 'קניות בגדים', 'בחנות'],
    photoAlts: ['שני עמיתים מחוץ לבניין משרדים', 'אישה בוחרת בגדים בחנות', 'אישה מתבוננת בחולצה בחנות'],
    videoScenes: ['קניות', 'זוג', 'פגישה'],
    videoAlts: ['אישה עורכת קניות בחנות', 'זוג מתבונן במסך', 'עמיתים בפגישת עבודה'],
    scene: 'בחירת סצנה', policy: 'בחירת רמת סינון', original: 'מקור', level: 'רמה', before: 'מקור', after: 'לאחר סינון', drag: 'גררו כדי להשוות בין המקור לתוצאה המסוננת',
    originalImage: 'התמונה המקורית. בחרו רמה כדי להשוות אותה לתוצאת הבדיקה.',
    originalVideo: 'הסרטון המקורי. בחרו רמה כדי לצפות בתוצאה המסוננת.',
    result: 'תוצאת הבדיקה', playOriginal: 'צפייה במקור', playFiltered: 'צפייה בתוצאה המסוננת', loading: 'טוען תצוגה מקדימה…',
    imageNote: 'בדיקות מבוקרות של תמונות באמצעות SAM 3.1. הדוגמאות אינן מעידות על זמינות כללית של השירות בייצור.',
    videoNote: 'סרטונים ללא קול מתוך בדיקות מבוקרות של הפרויקט. סרטוני החסימה הם חומרי המותג הרשמיים בכל שפה. הדוגמאות אינן מעידות על זמינות כללית בייצור.',
    imageLink: 'עוד על סינון תמונות', videoLink: 'עוד על סינון וידאו',
  },
  'pt-BR': {
    imageTitle: 'Veja o que muda em cada nível de imagem',
    imageIntro: 'Comece pela foto original. Escolha uma cena e um dos sete níveis; depois arraste a divisória para comparar o original com o resultado do teste.',
    videoTitle: 'Explore os seis níveis de filtragem de vídeo',
    videoIntro: 'Escolha um clipe e uma política, depois alterne entre o original e o resultado do teste. Nos níveis 5 e 6, o vídeo inteiro é substituído pelo vídeo de bloqueio do Browslium.',
    photoScenes: ['Colegas', 'Comprando roupas', 'Na loja'],
    photoAlts: ['Dois colegas em frente a um prédio comercial', 'Uma mulher escolhendo roupas em uma loja', 'Uma mulher olhando uma camisa em uma loja'],
    videoScenes: ['Compras', 'Casal', 'Reunião'],
    videoAlts: ['Uma mulher fazendo compras em uma loja', 'Um casal olhando para uma tela', 'Colegas em uma reunião'],
    scene: 'Escolha uma cena', policy: 'Escolha o nível de filtragem', original: 'Original', level: 'Nível', before: 'Original', after: 'Filtrado', drag: 'Arraste para comparar o original com o resultado filtrado',
    originalImage: 'Foto original. Escolha um nível para compará-la com o resultado do teste.',
    originalVideo: 'Clipe original. Escolha um nível para ver o resultado filtrado.',
    result: 'Resultado do teste', playOriginal: 'Ver original', playFiltered: 'Ver filtrado', loading: 'Carregando prévia…',
    imageNote: 'Testes controlados de imagens com SAM 3.1. Os exemplos não comprovam disponibilidade geral em produção.',
    videoNote: 'Clipes sem áudio de testes controlados do projeto. Os vídeos de bloqueio usam a mídia oficial da marca em cada idioma. Os exemplos não comprovam disponibilidade geral em produção.',
    imageLink: 'Conheça a filtragem de imagens', videoLink: 'Conheça a filtragem de vídeos',
  },
  fr: {
    imageTitle: 'Voyez ce que change chaque niveau de filtrage d’image',
    imageIntro: 'Commencez par la photo originale. Choisissez une scène et l’un des sept niveaux, puis déplacez la séparation pour comparer l’original au résultat du test.',
    videoTitle: 'Découvrez les six niveaux de filtrage vidéo',
    videoIntro: 'Choisissez un extrait et une règle, puis passez de l’original au résultat du test. Aux niveaux 5 et 6, la vidéo entière est remplacée par la vidéo de blocage Browslium.',
    photoScenes: ['Collègues', 'Achat de vêtements', 'En boutique'],
    photoAlts: ['Deux collègues devant un immeuble de bureaux', 'Une femme choisit des vêtements dans un magasin', 'Une femme regarde une chemise dans un magasin'],
    videoScenes: ['Achats', 'Couple', 'Réunion'],
    videoAlts: ['Une femme fait des achats dans un magasin', 'Un couple regarde un écran', 'Des collègues participent à une réunion'],
    scene: 'Choisir une scène', policy: 'Choisir un niveau de filtrage', original: 'Original', level: 'Niveau', before: 'Original', after: 'Filtré', drag: 'Déplacez le curseur pour comparer l’original au résultat filtré',
    originalImage: 'Photo originale. Choisissez un niveau pour la comparer au résultat du test.',
    originalVideo: 'Extrait original. Choisissez un niveau pour voir le résultat filtré.',
    result: 'Résultat du test', playOriginal: 'Voir l’original', playFiltered: 'Voir le résultat filtré', loading: 'Chargement de l’aperçu…',
    imageNote: 'Tests contrôlés d’images avec SAM 3.1. Ces exemples ne prouvent pas la disponibilité générale de la fonction en production.',
    videoNote: 'Extraits sans son issus de tests contrôlés du projet. Les vidéos de blocage sont les médias officiels de la marque dans chaque langue. Ces exemples ne prouvent pas la disponibilité générale en production.',
    imageLink: 'Découvrir le filtrage d’images', videoLink: 'Découvrir le filtrage vidéo',
  },
};
