// Copy for the same approved photo/video test galleries in all seven editions.
// These examples are controlled renders, not a claim of released filtering.
export const showcase = {
  en: {
    imageTitle: 'See what each image level changes',
    imageIntro: 'Choose a photo and one of seven levels. Move the divider to see how the selected level changes the image.',
    videoTitle: 'Watch the six video policies',
    videoIntro: 'Choose a video and one of six levels. Switch between the original and filtered views to see the difference.',
    photoScenes: ['Colleagues', 'Clothes shopping', 'In the store'],
    photoAlts: ['Two colleagues standing outside an office', 'A woman browsing clothes in a store', 'A woman looking at a shirt in a store'],
    videoScenes: ['Shopping', 'Couple', 'Meeting'],
    videoAlts: ['A woman shopping in a store', 'A couple looking at a screen', 'Colleagues in a meeting'],
    scene: 'Choose a scene', policy: 'Choose a filtering level', original: 'Original', level: 'Level', before: 'Original', after: 'Filtered', drag: 'Drag to compare the original with the filtered result',
    originalImage: 'Original photograph. Choose a level to see how it changes.',
    originalVideo: 'Original video. Choose a level to see how it changes.',
    result: 'Test result', playOriginal: 'Watch original', playFiltered: 'Watch filtered', loading: 'Loading preview…',
    imageNote: 'Controlled SAM 3.1 image tests. These examples do not establish general production availability.',
    videoNote: 'Silent clips from controlled project tests. Blocking videos use official localized brand media. These examples do not establish general production availability.',
    imageLink: 'Explore image filtering', videoLink: 'Explore video filtering',
  },
  es: {
    imageTitle: 'Mira qué cambia en cada nivel de imagen',
    imageIntro: 'Elige una foto y uno de los siete niveles. Desliza la línea para ver cómo cambia la imagen.',
    videoTitle: 'Explora los seis niveles de vídeo',
    videoIntro: 'Elige un video y uno de los seis niveles. Alterna entre el original y la versión filtrada para ver la diferencia.',
    photoScenes: ['Colegas', 'De compras', 'En la tienda'],
    photoAlts: ['Dos colegas frente a un edificio de oficinas', 'Una mujer mira ropa en una tienda', 'Una mujer observa una camisa en una tienda'],
    videoScenes: ['De compras', 'Pareja', 'Reunión'],
    videoAlts: ['Una mujer compra en una tienda', 'Una pareja mira una pantalla', 'Colegas participan en una reunión'],
    scene: 'Elige una escena', policy: 'Elige un nivel de filtrado', original: 'Original', level: 'Nivel', before: 'Original', after: 'Filtrado', drag: 'Arrastra para comparar el original con el resultado filtrado',
    originalImage: 'Foto original. Elige un nivel para ver cómo cambia.',
    originalVideo: 'Vídeo original. Elige un nivel para ver el resultado filtrado.',
    result: 'Resultado de la prueba', playOriginal: 'Ver original', playFiltered: 'Ver filtrado', loading: 'Cargando vista previa…',
    imageNote: 'Pruebas controladas de imágenes con SAM 3.1. Estos ejemplos no acreditan disponibilidad general en producción.',
    videoNote: 'Vídeos sin audio de pruebas controladas del proyecto. Los bloqueos usan los medios oficiales de marca en cada idioma. Estos ejemplos no acreditan disponibilidad general en producción.',
    imageLink: 'Conoce el filtrado de imágenes', videoLink: 'Conoce el filtrado de vídeo',
  },
  ru: {
    imageTitle: 'Как меняется изображение на каждом уровне',
    imageIntro: 'Выберите фото и один из семи уровней. Передвиньте линию, чтобы увидеть, как изменится изображение.',
    videoTitle: 'Шесть уровней фильтрации видео',
    videoIntro: 'Выберите ролик и один из шести уровней. Переключайтесь между исходной и отфильтрованной версиями.',
    photoScenes: ['Коллеги', 'Выбор одежды', 'В магазине'],
    photoAlts: ['Двое коллег у офисного здания', 'Женщина выбирает одежду в магазине', 'Женщина рассматривает рубашку в магазине'],
    videoScenes: ['Покупки', 'Пара', 'Совещание'],
    videoAlts: ['Женщина делает покупки в магазине', 'Пара смотрит на экран', 'Коллеги на совещании'],
    scene: 'Выберите сцену', policy: 'Выберите уровень фильтрации', original: 'Оригинал', level: 'Уровень', before: 'Оригинал', after: 'После фильтрации', drag: 'Переместите ползунок для сравнения оригинала и результата фильтрации',
    originalImage: 'Исходное фото. Выберите уровень, чтобы увидеть изменения.',
    originalVideo: 'Исходный ролик. Выберите уровень, чтобы посмотреть результат фильтрации.',
    result: 'Результат теста', playOriginal: 'Смотреть оригинал', playFiltered: 'Смотреть после фильтрации', loading: 'Загрузка примера…',
    imageNote: 'Контролируемые тесты изображений с SAM 3.1. Примеры не подтверждают общую доступность функции в рабочем продукте.',
    videoNote: 'Ролики без звука из контролируемых тестов проекта. Для блокировки используются официальные видеоматериалы на соответствующем языке. Примеры не подтверждают общую доступность функции в рабочем продукте.',
    imageLink: 'Подробнее о фильтрации изображений', videoLink: 'Подробнее о фильтрации видео',
  },
  yi: {
    imageTitle: 'זעט וואָס יעדער בילד־ניוואָ ענדערט',
    imageIntro: 'קלײַבט אַ פֿאָטאָ און איינעם פֿון די זיבן ניוואָען. רוקט די ליניע צו זען ווי דאָס בילד ענדערט זיך.',
    videoTitle: 'זעט די זעקס ווידעאָ־ניוואָען',
    videoIntro: 'קלײַבט אַ ווידעאָ און איינעם פֿון די זעקס ניוואָען. בײַט צווישן דעם אָריגינעל און דעם געפֿילטערטן ווידעאָ.',
    photoScenes: ['קאָלעגעס', 'קליידער קויפֿן', 'אין קראָם'],
    photoAlts: ['צוויי קאָלעגעס פֿאַר אַן אָפֿיס־בנין', 'אַ פֿרוי קוקט קליידער אין אַ קראָם', 'אַ פֿרוי קוקט אַ העמד אין אַ קראָם'],
    videoScenes: ['אײַנקויפֿן', 'פּאָרפֿאָלק', 'זיצונג'],
    videoAlts: ['אַ פֿרוי קויפֿט אײַן אין אַ קראָם', 'אַ פּאָר קוקט אויף אַן עקראַן', 'קאָלעגעס אין אַ זיצונג'],
    scene: 'קלײַבט אויס אַ סצענע', policy: 'קלײַבט אויס אַ פֿילטער־ניוואָ', original: 'אָריגינעל', level: 'ניוואָ', before: 'אָריגינעל', after: 'געפֿילטערט', drag: 'רוקט דעם טיילער צו פֿאַרגלײַכן דעם אָריגינעל מיטן געפֿילטערטן רעזולטאַט',
    originalImage: 'אָריגינעלער פֿאָטאָ. קלײַבט אַ ניוואָ צו זען דעם חילוק.',
    originalVideo: 'אָריגינעלער קליפּ. קלײַבט אַ ניוואָ צו זען דעם געפֿילטערטן רעזולטאַט.',
    result: 'פּרוּוו־רעזולטאַט', playOriginal: 'זען אָריגינעל', playFiltered: 'זען געפֿילטערט', loading: 'דער בײַשפּיל ווערט געלאָדן…',
    imageNote: 'קאָנטראָלירטע בילד־פּרוּוון מיט SAM 3.1. די בײַשפּילן באַשטעטיקן נישט אַז די פֿונקציע איז שוין אַלגעמיין בנימצא.',
    videoNote: 'שטומע קליפּס פֿון קאָנטראָלירטע פּרוּוון פֿונעם פּראָיעקט. די בלאָקירווידעאָס זענען די אָפֿיציעלע מאַטעריאַלן אין יעדער שפּראַך. די בײַשפּילן באַשטעטיקן נישט אַלגעמיינע פֿאַרפֿיגבאַרקייט.',
    imageLink: 'מער וועגן בילד־פֿילטרירונג', videoLink: 'מער וועגן ווידעאָ־פֿילטרירונג',
  },
  he: {
    imageTitle: 'ראו מה משתנה בכל רמת סינון תמונות',
    imageIntro: 'בחרו תמונה ואחת משבע הרמות. גררו את קו ההפרדה כדי לראות מה משתנה.',
    videoTitle: 'צפו בשש רמות סינון הווידאו',
    videoIntro: 'בחרו סרטון ואחת משש הרמות. עברו בין הגרסה המקורית למסוננת כדי לראות את ההבדל.',
    photoScenes: ['עמיתים לעבודה', 'קניות בגדים', 'בחנות'],
    photoAlts: ['שני עמיתים מחוץ לבניין משרדים', 'אישה בוחרת בגדים בחנות', 'אישה מתבוננת בחולצה בחנות'],
    videoScenes: ['קניות', 'זוג', 'פגישה'],
    videoAlts: ['אישה עורכת קניות בחנות', 'זוג מתבונן במסך', 'עמיתים בפגישת עבודה'],
    scene: 'בחירת סצנה', policy: 'בחירת רמת סינון', original: 'מקור', level: 'רמה', before: 'מקור', after: 'לאחר סינון', drag: 'גררו כדי להשוות בין המקור לתוצאה המסוננת',
    originalImage: 'התמונה המקורית. בחרו רמה כדי לראות מה משתנה.',
    originalVideo: 'הסרטון המקורי. בחרו רמה כדי לצפות בתוצאה המסוננת.',
    result: 'תוצאת הבדיקה', playOriginal: 'צפייה במקור', playFiltered: 'צפייה בתוצאה המסוננת', loading: 'טוען תצוגה מקדימה…',
    imageNote: 'בדיקות מבוקרות של תמונות באמצעות SAM 3.1. הדוגמאות אינן מעידות על זמינות כללית של השירות בייצור.',
    videoNote: 'סרטונים ללא קול מתוך בדיקות מבוקרות של הפרויקט. סרטוני החסימה הם חומרי המותג הרשמיים בכל שפה. הדוגמאות אינן מעידות על זמינות כללית בייצור.',
    imageLink: 'עוד על סינון תמונות', videoLink: 'עוד על סינון וידאו',
  },
  'pt-BR': {
    imageTitle: 'Veja o que muda em cada nível de imagem',
    imageIntro: 'Escolha uma foto e um dos sete níveis. Arraste a divisória para ver o que muda na imagem.',
    videoTitle: 'Explore os seis níveis de filtragem de vídeo',
    videoIntro: 'Escolha um vídeo e um dos seis níveis. Alterne entre as versões original e filtrada para ver a diferença.',
    photoScenes: ['Colegas', 'Comprando roupas', 'Na loja'],
    photoAlts: ['Dois colegas em frente a um prédio comercial', 'Uma mulher escolhendo roupas em uma loja', 'Uma mulher olhando uma camisa em uma loja'],
    videoScenes: ['Compras', 'Casal', 'Reunião'],
    videoAlts: ['Uma mulher fazendo compras em uma loja', 'Um casal olhando para uma tela', 'Colegas em uma reunião'],
    scene: 'Escolha uma cena', policy: 'Escolha o nível de filtragem', original: 'Original', level: 'Nível', before: 'Original', after: 'Filtrado', drag: 'Arraste para comparar o original com o resultado filtrado',
    originalImage: 'Foto original. Escolha um nível para ver o que muda.',
    originalVideo: 'Clipe original. Escolha um nível para ver o resultado filtrado.',
    result: 'Resultado do teste', playOriginal: 'Ver original', playFiltered: 'Ver filtrado', loading: 'Carregando prévia…',
    imageNote: 'Testes controlados de imagens com SAM 3.1. Os exemplos não comprovam disponibilidade geral em produção.',
    videoNote: 'Clipes sem áudio de testes controlados do projeto. Os vídeos de bloqueio usam a mídia oficial da marca em cada idioma. Os exemplos não comprovam disponibilidade geral em produção.',
    imageLink: 'Conheça a filtragem de imagens', videoLink: 'Conheça a filtragem de vídeos',
  },
  fr: {
    imageTitle: 'Voyez ce que change chaque niveau de filtrage d’image',
    imageIntro: 'Choisissez une photo et l’un des sept niveaux. Déplacez la séparation pour voir comment l’image change.',
    videoTitle: 'Découvrez les six niveaux de filtrage vidéo',
    videoIntro: 'Choisissez une vidéo et l’un des six niveaux. Passez de l’original à la version filtrée pour voir la différence.',
    photoScenes: ['Collègues', 'Achat de vêtements', 'En boutique'],
    photoAlts: ['Deux collègues devant un immeuble de bureaux', 'Une femme choisit des vêtements dans un magasin', 'Une femme regarde une chemise dans un magasin'],
    videoScenes: ['Achats', 'Couple', 'Réunion'],
    videoAlts: ['Une femme fait des achats dans un magasin', 'Un couple regarde un écran', 'Des collègues participent à une réunion'],
    scene: 'Choisir une scène', policy: 'Choisir un niveau de filtrage', original: 'Original', level: 'Niveau', before: 'Original', after: 'Filtré', drag: 'Déplacez le curseur pour comparer l’original au résultat filtré',
    originalImage: 'Photo originale. Choisissez un niveau pour voir ce qui change.',
    originalVideo: 'Extrait original. Choisissez un niveau pour voir le résultat filtré.',
    result: 'Résultat du test', playOriginal: 'Voir l’original', playFiltered: 'Voir le résultat filtré', loading: 'Chargement de l’aperçu…',
    imageNote: 'Tests contrôlés d’images avec SAM 3.1. Ces exemples ne prouvent pas la disponibilité générale de la fonction en production.',
    videoNote: 'Extraits sans son issus de tests contrôlés du projet. Les vidéos de blocage sont les médias officiels de la marque dans chaque langue. Ces exemples ne prouvent pas la disponibilité générale en production.',
    imageLink: 'Découvrir le filtrage d’images', videoLink: 'Découvrir le filtrage vidéo',
  },
};
